### ISSUE TITLE
instapaper import fails

### ISSUE THREAD

**Issue by dropmeaword** [wallabag/wallabag#1071]
Trying to import the HTML output file from instapaper into wallabag seems to fail. I have about 360 links, but only 140 appear on my list after the import, most of them do not have any content. Even after clicking on the "fetch content for articles with no content" link, it doesn't seem to update the content. There are no error messages on the interface and nothing to be seen on the php error_log. So I am at a loss.

How can I use the API to make my own import script? Any attempt to post to "POST /api/entries" is met with a login page?

I am using wallabag 1.8.1.

**Comment by tcitworld** [comment]
API is only available with v2, currently on development.
You may want to play with some IMPORT constants in the inc/poche/config.inc.php. Maybe some timeout errors are not displayed if error level is not set to E_ALL in your php.ini

Since we are focused on v2, I don't think we will make some (big) changes to the import system. Sorry about that.

Anyway, the only "miracle" solution I see is manually splitting the file into more files.

**Comment by tcitworld** [comment]
Next minor version should fix things a bit before v2.

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
