### ISSUE TITLE
How do I add new user without the interface after installation.

### ISSUE THREAD

**Issue by mathwhiz1212** [wallabag/wallabag#1092]
I deleted my account (bad idea I now see) and now I can't log into the wallabag installation. how do I create a new user?
Wallabag V.1.8.1, PHP  5.4.36, mysql  Ver 14.14

**Comment by tcitworld** [comment]
You've got to use phpMyAdmin or the mysql console and create a new row in the users table with : 
* your username
* your salted password = the sha1 of (yourpassword + your username + your salt available in the config file inc/poche/config.inc.php). *To obtain the sha1, you can use [this tool](http://www.sha1-online.com/). For instance, `passwordloginsalt` gives `1bbc43879ee7fb5c78c8dcefee1f9f31d0ffe4f2`
* your username again... for some reason I can't see why
* your email eventually, or leave blank

**Comment by mathwhiz1212** [comment]
Will keep this in a file for future reference, I was impatient and reinstalled.

**Comment by dk3775** [comment]
Does it still work same way? because I can see 2 colomns in my wllf_user table 
- salt
- password

I generated the sha1 as you mentioned but  it looks like the replacement for the salt, so what do I replace with password?


* I have an active login in my phone so I will export the stuff and create new installation for now. But I am curious to know this.

**Comment by j0k3r** [comment]
This is not the way to do it.
That issue was related to wallabag v1.
In v2, you should use `php bin/console fos:user:create`

I'm locking that issue to avoid futher mistake from user.
