### ISSUE TITLE
Wallabag using WordPress

### ISSUE THREAD

**Issue by skynet** [wallabag/wallabag#1112]
I have a crazy idea: 

How about building Wallabag on top of WordPress, using its PressThis NEW plugin: 
https://wordpress.org/plugins/press-this/

Most of functionality and features that you are trying to achieve with Wallabag have a foundation in Wordpress. Tags, for example. Or, selecting images. This feature is already working with the WP bookmarklet, and not available yet with the Wallabag browser extension button.

You can simply pack a Wp+Wallabag (plugin + theme) bundle. Even more, you can focus on the browser extensions and mobile apps, something that WordPress is way behind with.

More info here:
https://make.wordpress.org/core/2015/02/18/press-this-revamp-merge-proposal/
and here:
http://en.support.wordpress.com/press-this/

**Comment by tcitworld** [comment]
Er, I'm not sure I have understood this idea, and I really don't see what's the advantage.

**Comment by skynet** [comment]
I explained everything above. I get the feeling that you won't be able to implement and support all sort of related functionality if you can't leverage on a framework built for content management.

**Comment by tcitworld** [comment]
As of today, none of us is interested by making a business model with wallabag. 

You're right on a point : wallabag, with current architecture, is limited in features. That's why we did choose the next version (v2) to be completely rebased with the Symfony framework. See the paragraph *Future of wallabag* in [this blog post](https://www.wallabag.org/blog/2015/02/18/wallabag-1-9-many-features).

But if some people would say using Symfony too much for such a project, I **personally** think basing wallabag on Wordpress is really kind of using a sledgehammer to crack a nut.

Ping @nicosomb and @j0k3r

**Comment by tcitworld** [comment]
Your second paragraph brings questions, though. We may have to discuss it.

**Comment by skynet** [comment]
Thanks, appreciate your openness. I sincerely hope to see something better than Pocket. I also envision something as smart as [Prismatic](http://getprismatic.com/) where you can bring Wallabag bookmarks into the Interest Graph API.

**Comment by tcitworld** [comment]
Thanks for the link, their API seems to be exactly what we were looking for auto-tagging articles (#1111). We would have preferred an open-source solution, but if it gives good results, we'll use it.

**Comment by j0k3r** [comment]
Well, your idea @skynet is of course interesting and that's why Symfony was chosen to build the v2. It will help us have:
 - a better structure and model
 - a lot of tests to avoid regression
 - a solid base to build new feature
 - a real API
 - the ability to welcome any new developper (since sf2 is pretty popular)

Anyway it will leverage wallabag to a new level. I don't think Wordpress could be a good idea to do that. There will be too much thing we won't use and too much we'll have to break to implement wallabag feature, etc ..

**Comment by skynet** [comment]
Makes sense, Symphony was a great idea. Lot of work though, so make it worth. Good luck!

**Comment by j0k3r** [comment]
You can follow the work here: https://github.com/wallabag/wallabag/pull/1049
And there is a blogpost about that: https://framasphere.org/posts/391087
