### ISSUE TITLE
Saving URL from FeedaFever

### ISSUE THREAD

**Issue by tgrosinger** [wallabag/wallabag#1169]
wallabag version: 1.9.0
Server version: Apache/2.4.7 (Ubuntu)
Storage: mysql  Ver 15.1 Distrib 5.5.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

From [Fever](http://feedafever.com/) I am able to setup custom share shortcuts and am given a "%u" as a placeholder for the URL. I am using https://myhostname/wallabag/?action=add&autoclose=true&url=%u as the share link.

Here is an example URL that actually gets sent:

https://firefly.grosinger.net/wallabag/?action=add&autoclose=true&url=https%3A%2F%2Fblog.plex.tv%2F2015%2F01%2F20%2Fplex-ps3-ps4-now-available-north-south-america%2F

And the resulting page I see simply says "Invalid URL supplied"

**Comment by tcitworld** [comment]
If you supply the URL via the `url` parameter, you first need to encode it with base64. If you can't, you can use the `plainurl` parameter.

**Comment by tgrosinger** [comment]
`plainurl` is working. Thank you

**Comment by packetgeek** [comment]
Had similar issue.  Had written Perl script using MIME::Base64 encoder.  Worked find with:

    http://delyan.me/securing-ssh-with-totp/

But would truncate the following after the first dash:

    http://blogs.msdn.com/b/vcblog/archive/2015/11/18/announcing-the-vs-gdb-debugger-extension.aspx

Switched to "plainurl" and it works (still testing).  Assumption is that problem lies in the Perl encoder and not Wallabag.  Thanks for including "plainurl" btw.
