### ISSUE TITLE
unable to retrieve full-text content from robchapman.tv

### ISSUE THREAD

**Issue by lupinehorror** [wallabag/wallabag#1205]
trying to save the link

http://www.robchapman.tv/forum/threads/finish.32265/#post-638079

using the firefox extension but the same thing happens using android. result is:

Untitled
Estimated reading time: < 1 min

```
Toggle mark as read
Toggle favourite
Delete
www.robchapman.tv
```

[unable to retrieve full-text content]...

this has happened with other sites too (slashdot for example)

**Comment by tcitworld** [comment]
Saving (and parsing !) forums is quite hard, I don't think I can manage to write proper rules files for this.

**Comment by 0wnrepo** [comment]
Isn't it possible to save (the original page) only, but not parse the content ? Something like a full offline copy of that page ?

**Comment by tcitworld** [comment]
Well, it's not really the intent of the app. If you want full backups, tools exist for that. If we saved, then displayed the whole original page inside wallabag, it would be quite dirty.

I understand it's bothering when we can't parse the page and no content is retrieved, but that's because the website's code is badly written and we make specific rules for those websites.

**Comment by 0wnrepo** [comment]
Sorry for the offtopic, but if one would make such a change, to download and view either the parsed option / or the original version, would it be accepted in the code review ?

**Comment by tcitworld** [comment]
Well, we thought of having a plugin system in the future. But for now, a simple option to have this would be fine. However, it would be quite hard to be done (for instance, dealing with the original css and our own, with menus,...). If you're interested, we can talk about it on https://gitter.im/wallabag/wallabag.
