### ISSUE TITLE
Use Mozilla Interest Dashboard for metadata on websites.

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#1412]
https://github.com/mozilla/interest-dashboard

Maybe this can be made directly with https://github.com/j0k3r/graby

**Comment by j0k3r** [comment]
You mean, getting information from the Wallabag database to _materialize_ them as a nice dashboard, like Mozilla Interest Dashboard?

Because Mozilla Interest Dashboard use Firefox history to build graphs. We don't have browser history except in Wallabag database. IMHO graby has nothing to do with that. Or I don't get the point ..

**Comment by tcitworld** [comment]
Not at all, I mean use the data in the refData directory to provide metadata for domains. Will explain with more  details later.

**Comment by Kdecherf** [comment]
The linked repository does not have any activity since 2015 and the add-on page is now missing.

I'm closing this issue as there's a lack of activity.

**Comment by tcitworld** [comment]
> 9 Sep 2015
> later

😅
