### ISSUE TITLE
Simple bookmarks list, not downloading content

### ISSUE THREAD

**Issue by mlanner** [wallabag/wallabag#1456]
Just found Wallabag today and installed it on a VM server. It's a great piece of software!

One feature I was hoping would be available, in addition to the Pocket-like functionality, was to be able to just store a bunch of "standard" bookmarks, like: https://mysite.com, but not actually downloading the content. Maybe I'm just missing or misunderstanding how it should/could be used?

If the feature above is actually not available, would you take it into consideration just creating a tab simply called "Bookmarks"? While I do **really** like the "full" functionality, having a bookmarks section too would be fantastic.

Thanks in advance!

**Comment by tcitworld** [comment]
Well, it's definitely not the main aim of the app. I guess some floss tools already exist to do the job.

However, you're not the first to ask it, and it could be something that we would consider (as the evernote-like feature) in the future.

**Comment by mlanner** [comment]
@tcitworld Thanks for the incredibly quick response. I get that it's not the main focus. Fair enough. I still think it would make Wallabag even better. I'm definitely going to to continue evaluating and using Wallabag.

(Sidebar: I've been looking for self-hosted floss tools that do similar things to what Delicious does, but most of them are shut down and/or haven't seen any updates in five or more years.)

**Comment by tcitworld** [comment]
> (Sidebar: I've been looking for self-hosted floss tools that do similar things to what Delicious does, but most of them are shut down and/or haven't seen any updates in five or more years.)

Have you tried https://github.com/shaarli/Shaarli ? It's quite good and active.

**Comment by mlanner** [comment]
Looks good (in terms of features/functionality). I had seen Shaarli before, but I guess I had only seen the old un-maintained project. I'll probably give Shaarli a run too. Thx for the tip.

**Comment by tcitworld** [comment]
The original creator doesn't make any changes since he thinks its state is sufficient (kiss philosophy), that's why it seems abandoned at first.

**Comment by j0k3r** [comment]
From my POV, wallabag isn't designed to be a bookmark service, even if you can use it like that.

What you can simply do, whenever you add a link as a bookmark, you can let wallabag grab the content (because you don't care) and just add a tag _bookmark_ to it. So you can easily retrieve all your bookmarks using this tag.

It remains me [Pinboard](https://pinboard.in/). When I paid for a Pinboard account the main feature was (and still be) to cache each of your bookmark. So when an url you bookmarked long time ago goes down, offline or the website is gone forever, you still have your article and you can still read it, share it ... From POV, it's a killer feature. And wallabag can do that :smile:

**Comment by nicosomb** [comment]
Yes, @j0k3r is right, wallabag is not a bookmark app and it's not planned to be one. I close this PR and as @tcitworld said, shaarli is a great software to do that.
