### ISSUE TITLE
[v2] Issue with PostgreSQL, table prefixes and `user` table

### ISSUE THREAD

**Issue by black-roland** [wallabag/wallabag#1498]
Hi.

I have a problem with user creation using PostgreSQL database without table prefix:

```
$ php app/console wallabag:install

<...>

[PDOException]                                                           
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "user"  
LINE 1: INSERT INTO user (username, username_canonical, email, email...
```

Part of my `app/config/parameters.yml`:

```
parameters:
    database_driver: pdo_pgsql
    database_table_prefix: null
```

`user` word reserver by PostgreSQL internals and must be escaped: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words

I tried to fix problem by myself, but without success: https://github.com/black-roland/wallabag/commit/34b32a322b527a8700b0ee28ddec18c3ca9c4727 `Doctrine\ORM\Mapping\DefaultQuoteStrategy` checks for `$class->table['quoted']`, but I can't set `@ORM\Table(quoted=true)` annotation: https://github.com/black-roland/wallabag/commit/34b32a322b527a8700b0ee28ddec18c3ca9c4727#diff-60178373aeaf91c2ae95921e03b3ca39R22

Please help with bugfixing :)

Thanks.

**Comment by nicosomb** [comment]
Hello @black-roland!

Thanks for your report. We'll fix it. 
Why can't you use prefix? 

Just to tell that installation with PostegreSQL and table prefix works, we use PostgreSQL for http://v2.wallabag.org ;-)

**Comment by black-roland** [comment]
> Why can't you use prefix?

I can. Table prefixes are typically used on hostings with single database without possibility of creating separated database. In my case I have a separate database and I disabled prefix.

Issue may occur in the future with column names (not only with table names).

P.S. With tables prefix Wallabag workds fine. Thanks for the support.

**Comment by j0k3r** [comment]
I looked into that this morning.
You were in a good way to solve the problem using the default quote strategy. I used the same to reproduce the bug. You hit the most **not obvious part** of the quoted system :)

The `quoted` attribute doesn't exist in the Mapping Table, that's why you got an error. In fact, this attribute is added later in case of the table name starts with ` which is usually used to _escape_ table name, etc .. 

:arrow_right: [lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L1393-L1396](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L1393-L1396)

So I tried to define the table name like that for each entity, and I don't have to define the quote strategy like you did, since the `DefaultQuoteStrategy` is enabled by default:

```php
@ORM\Table(name="`user`")
```

The table name is well _escaped_, I got some `CREATE TABLE "user" (id INT NOT NULL,`.

But then, it avoid our prefix naming strategy. It simply doesn't look at it when it generates the table name. Which is sad.

So instead of using the built-in way from Doctrine to prefix table, I switched to a Subscriber (as defined [here](http://stackoverflow.com/a/8366548/569101)).

You can follow this stuff on this PR: #1500

**Comment by j0k3r** [comment]
Also, there is no _complex_ test on that InstallCommand because it usually kills the test suite on Travis because it manipulates database, etc ... That's why the test suite is launched like that on Travis:

```
bin/phpunit --exclude-group command-doctrine -v
```

Which excludes test that manipulate the database using this command.
Instead of that, maybe it's better to launch PHPunit a second time only for the command, we'll see what can I do.
