### ISSUE TITLE
Bring annotations to API

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabag#1800]
In the current beta there's an inconsistency when it comes to the API. All methods are available under `URL/api/SOMETHING`. However the API for the annotations is available under `URL/annotations` and therefore without the `api` substring. In terms of consistency the annotations API should be available under `URL/api/annotations`, too :)

**Comment by tcitworld** [comment]
That's because for now the annotation API is only for the web interface (ajax calls to [Annotator](http://docs.annotatorjs.org/en/latest/modules/storage.html)). It shouldn't be shown in the documentation for now.

However, when I'll do the work of serving them through our API, the doc shouldn't be much different.
