### ISSUE TITLE
Download pictures on my webserver

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2033]
When I save a new article, I want that wallabag downloads article's pictures in my `data` folder. 

This feature already exists in wallabag v1.x.

**Comment by Alixerid** [comment]
Related to this feature: I saw that browsers show the "mixed content" warning despite the wallabag installation being secured with TLS (https). Pulling the images from third party servers and not serving them from wallabag instance should be the reason for the warning.
i.e. +1 for this also due to TLS security.
