### ISSUE TITLE
Shouldn't update an article if it cannot retrieve the content anymore

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#2101]
### Issue details

As explained in the issue #2100 I had this article fetched from lwn.net when I was using wallabag 1.x that I imported when I migrated to w 2.x with all other articles, which cannot being fetched nowaday.
Should wallabag prevent to update the content of the article if it cannot retrieve the content anymore.
### Environment
- wallabag version (or git revision): 2.0.4
- How did you install wallabag: `git clone`
- Last wallabag version that did not exhibit the issue: N//A
- php version: 7.0
- OS: Ubuntu 16.04
- type of hosting: dedicated
- which storage system you choose at install: MySQL:
### Steps to reproduce/test case
- Fetch a page from lwn.net with wallabag 1.X
- export the data and import it to a wallabag instance 2.0.x
- Fetch the page from the wallabag 2.0.x
- Wallabag informs it cannot retrieve the content of the page.

**Comment by j0k3r** [comment]
Yeah it could be a good alternative to avoid loosing data from previous version.

**Comment by j0k3r** [comment]
It's an old issue but refetching a content with the reload feature doesn't update the html when refetching failed (see https://github.com/wallabag/wallabag/pull/2482).

When using the v1 import, we don't refetch content from the website (for the moment, see https://github.com/wallabag/wallabag/issues/1842).

AFAIK it looks like this issue is fixed, can you confirm @bmillemathias?

**Comment by nicosomb** [comment]
We also have this issue "If parsing fails, just redirects to the article" https://github.com/wallabag/wallabag/issues/1387
