### ISSUE TITLE
API POST makes duplicates

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#2232]
### Issue details

API POST makes duplicates if url doesn't end with slash
### Environment

wallabag version : 2+
### Steps to reproduce/test case

"https://habrahabr.ru/company/intel/blog/283066" adds as many times as call,
"https://habrahabr.ru/company/intel/blog/283066/" returns the first

**Comment by j0k3r** [comment]
Technically it's not the same url :trollface:

**Comment by Rurik19** [comment]
Right, but wallabag saves all urls WITH ending slash and then cannot find it :)

**Comment by j0k3r** [comment]
So, we have an issue here.

When a user put an url (or when it came from the API), we check if that exact url exists into our database. If it exists, we don't insert it.
If not, we start the engine and grab information from that url. One information is the _effective_ url, which mean, the final url (after redirection for example). And we store that final url (and content, etc.) into the database.

With an example: if user try to put a bit.ly url into the url field, we won't store that bit.ly url but the final url (the one which redirect to). So, if user put that exact same bit.ly url again, we won't find it in the database (so we won't say _it already exist_) and we'll save the content again.

One possible solution could be to re-check the url after grabbing all information from the url. Which means we'll check with the final url. **BUT** this won't work with the API endpoint `exists` because for that one we only check the given url (not the final one). Or maybe we should grab information from that url and re-check too. But this will cost a lot of time for an endpoint which should be fast.

Thoughts @wallabag/core ?

**Comment by nicosomb** [comment]
> Thoughts @wallabag/core ?

Oh, I missed your post. 

Do we have other solutions? 
In a first time, we can do that for the web application.

**Comment by Kdecherf** [comment]
We could have a new table which registers all url that translate to a given final url. Thoughts?

**Comment by j0k3r** [comment]
Why not it could be an idea. We should have a user_id too and might sure to remove urls when the associated entry is removed.

**Comment by Rurik19** [comment]
New table is a spare thing. I think the "original_url" field in the entry table would be enought.

**Comment by nicosomb** [comment]
I'm not sure that I want a new table. 
But just a single new field can be binding: if we have many URL for a single original URL, how can we handle this?

**Comment by Rurik19** [comment]
@nicosomb 

>if we have many URL for a single original URL,  can we handle this?

they all will be in separate entries, in url fiels so if we nees to get all url of one original - that will be easy (with an index on original_url field)

**Comment by Kdecherf** [comment]
@nicosomb what is the issue with the addition of a new table?

@Rurik19 this implies to have duplicates of the same article or I didn't understand how do you want to handle origin_url field.

**Comment by tcitworld** [comment]
> this implies to have duplicates of the same article

From my pov, the `/exists/` API (and wallabag through interface too) would check in both `url` and `original_url` fields. No clue about performance though.

**Comment by Kdecherf** [comment]
Yep, I understand that but how do we store more than one original url for the same article without a separate table?

**Comment by Rurik19** [comment]
@tcitworld I think exists should check only original_url, because there are may be many different shorten-url for one page

**Comment by tcitworld** [comment]
My bad, so we do need indeed a new table if we don't want duplicates all over our `entries` table. Hope we can do that with minimum performance issues.

**Comment by Kdecherf** [comment]
Let's make some benchmarking

**Comment by nicosomb** [comment]
> what is the issue with the addition of a new table?

I don't know what is the issue. 
But I'm not a fan of adding new tables. (new tables = new migrations = maintain them = etc...)

**Comment by tcitworld** [comment]
Just like adding a column...

**Comment by Crell** [comment]
Perhaps I'm missing something here, but why the need to track the original URL?  If a URL is submitted, resolve it down to its for-reals URL after redirects and then check that.  End of story, kthxbye.

I realize that may sometimes involve an extra HTTP request or two, but those are reasonably cheap much of the time, especially if you just send HEAD requests until you get back a 200, then send a GET for that.  It will be unusual for a page to redirect more than once, maybe twice if it goes through both Twitter's URL shortener and Bitly's shortener, but that's it.

**Comment by j0k3r** [comment]
Might be a good solution.
We prefered to store the url first to avoid making HTTP request at all (and extracted content etc.) before being able to say it's a duplicate. But this might be the solution.

**Comment by nicosomb** [comment]
This issue needs to be milestoned to minor release, due to new table/column, right?

**Comment by Eisfreak7** [comment]
Without actually resolving the URL something like `https://www.blog.com/articleoftheweek` (redirecting to a different article every week) could also be a problem.

**Comment by nicosomb** [comment]
FYI it should be fixed with #3271.
