### ISSUE TITLE
Failed make script

### ISSUE THREAD

**Issue by gerroon** [wallabag/wallabag#2517]
wallabag# make
scripts/install.sh: 8: scripts/install.sh: [[: not found
scripts/install.sh: 9: .: Can't open /require.sh
make: **\* [install] Error 2

Debian Wheezy Apache 2.2 Wallabag 
commit ca9858537eb0412994b42bdd7ea4f26f7cae96b2
Merge: 67b270d c4b3933
Author: Jeremy Benoist j0k3r@users.noreply.github.com
Date:   Sat Oct 29 15:36:58 2016 +0200

**Comment by j0k3r** [comment]
Hello dear wallabag user from the master unstable branch.

You know that we put a template for writing an issue?
That file: https://github.com/wallabag/wallabag/blob/master/.github/ISSUE_TEMPLATE.md

You probably didn't read it because you were in a hurry of posting the issue.
You just removed the whole stuff to put your unexpressive fast dropped error without any context or comment.

So should I just close your issue as fast as you opened it and dropped your problem? Or should I try to take time to answer you (time that I could spend working on wallabag instead, btw), well not technically answering you, because, since you removed the issue template you missed some questions we ask about how you got that problem, why do you got the problem, which version are you using, etc ...

I hope you'll also spend a well evening (this you asked for it).
👋
