### ISSUE TITLE
Store credentials for restricted site in database

### ISSUE THREAD

**Issue by j0k3r** [wallabag/wallabag#2636]
Following https://github.com/wallabag/wallabag/pull/2317 (ie: ability to retrieve content from a website using an user subscription), we now need to store login / password in database instead of parameters.

Since we are going to use these credentials, we can't encrypt them because we won't be able to re-use them later. So they'll be stored as plain text in the database.
We should warn user about that. Mostly if user use a SAAS service (which might share multiple user).

**Comment by tcitworld** [comment]
I am sad to see this will have to wait 2.3 if not in 2.2. Shouldn't we focus on this ? Having the credentials in the parameters in quite ridiculous since it's available only for people who self-host themselves.

**Comment by nicosomb** [comment]
We can focus on this feature, not a problem. 
I cleaned up the roadmap for 2.2: https://github.com/wallabag/wallabag/milestone/35

**Comment by j0k3r** [comment]
We still need to find the best way to store them.
Plain text is the final fallback but what could be a better solution to avoid that fallback?

**Comment by di72nn** [comment]
Use a randomized `secret` in parameters as a key to encrypt credentials stored in DB.

**Comment by ThibaudDauce** [comment]
When a restricted page is added into wallabag, show a form to the user to enter his credentials and perform the fetch in real time without saving them so the credentials stay on the server only for a request lifetime?

**Comment by nicosomb** [comment]
@ThibaudDauce It's an idea but as @j0k3r told me, this behavior is impossible with imports from other services.

**Comment by j0k3r** [comment]
@ThibaudDauce importing from the iOS / Android / Windows app will be a pain.
Also, how can we handle that when user import some content?

**Comment by ThibaudDauce** [comment]
Like Pocket? For me the article is saved with an empty content (or partial content) in the database and when the user read it for the first time, the credentials are asked. The mobile applications can also asked for credentials when they fetch new articles and notice restricted articles.

It's also possible to add a checkbox when the user add his credentials "Remember my credentials for this restricted website (warning, they'll be stored in plain text)" for people not interested in credential security.

**Comment by nicosomb** [comment]
The behavior needs to be the simplest possible.

**Comment by ThibaudDauce** [comment]
I was trying to think of a solution for not saving the passwords in plain text, but I fully understand that the "store in database" may be the best solution…

It could be a future improvement.

**Comment by jlnostr** [comment]
And what if a random generated salt is generated during installation/upgrade and wallabag encrypts/decrypts the credentials using AES for example?

**Comment by j0k3r** [comment]
I was thinking of sth like that.
But, some getting access to the wallabag server will be able to decrypt the key anyway

**Comment by jlnostr** [comment]
Even if the password from the user and the salt are combined, e.g. through a hash? Something like `password = sha256(username + salt)` should do the trick, shouldn't it?

**Comment by di72nn** [comment]
> And what if a random generated salt is generated during installation/upgrade and wallabag encrypts/decrypts the credentials using AES for example?

It is a frequently used method to store such data. It prevents someone who got access to the database (SQL-injection, etc.) to decrypt the data. Of course, it wouldn't add security if the attacker gets root access.

> `password = sha256(username + salt)`

This is either irreversible, or I don't get the idea.

**Comment by jlnostr** [comment]
No, you're right. It's irreversible. Oops.

**Comment by zertrin** [comment]
Reading the following sentence in the merge request:

> As of now, the password is stored in plain text in database. I don't find a reliable solution to encode it. Maybe we can generate a base64, but it's simple to decode.

I feel obligated to urge you to respect the one rule of crypto: "don't roll your own crypto".

Moreover, you don't seem to be versed into the correct terms and vocabulary related to cryptography. If the difference between encryption, encoding and hashing is not clear to you, just don't attempt to do it before you look it up properly and the difference becomes obvious.

Base64 is about encoding and has nothing to do with encryption at all. It is 100% equivalent to plaintext and brings 0% of security.

Now, concerning the solution to this issue, basically you have 2 solutions:
- the easy to implement one, where you will make no false security assumption: store the password in plaintext and be aware of it.
- the hard one where you have a high chance of messing it up and finish with erroneous claims of security: encryption of the password with an encryption key stored on the server side. (in this case, the problem is not only how to implement the encryption without mistake, but also how to secure the encryption key so that this complicated solution brings some more security that just storing the password plaintext)

I am no crypto expert, but I have taken the cryptography course of Dan Boneh on Coursera, and that was very interesting and made me understand how to spot crypto security that is not security.

Honestly, if you don't have a very good understanding of the field of cryptography, don't even try to do it yourself.

My advice here would be to stick with storing plaintext passwords until someone with good crypto skills (read "_someone whose dayjob is implementing crypto_") can implement something that is better than storing plaintext password.

There are examples of software that specialize in storing and retrieving secrets programmatically (for example Vault). If you look it up you'll see that this is no easy business, and there is a reason to that: that's just very hard business.

I hope you won't take this as condescending, I love wallabag and I like crypto. This is a genuine piece of advice to make wallabag better.

**Comment by nicosomb** [comment]
Hello @zertrin! 
Thank you so much for your explanations. We'll discuss about that with @j0k3r and @tcitworld soon.

**Comment by jcharaoui** [comment]
This complicated and hazardous feature idea would be completely unecessary if the Wallabag browser extension sent the DOM of the page to the Wallabag instance via the API, instead of sending only the URL and relying on the app to fetch the contents. And by the way, usernames, passwords and login URLs tend to change over time...

**Comment by di72nn** [comment]
@jcharaoui I have to point out that browser extensions are not the only wallabag clients and it is not always possible/convenient for a client to fetch content by itself.

**Comment by j0k3r** [comment]
Hey guys, I'm back on working on that issue.

What do you think of that solution on encrypting password?
https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md#scenario-2-encrypting-account-data-with-the-users-login-password

(courtesy from https://github.com/wallabag/wallabag/pull/2683#issuecomment-298563659)

**Comment by tcitworld** [comment]
Issues I see with this : 
* We need to get user's password before it's hashed by Symfony. Quite feasible but may introduce security issues. :boom: 
* Can't be used through API, unless : 
  * We create a new key for each API client, or
  * We hack things to kind of whitelist API calls through a dedicated key...

**Comment by di72nn** [comment]
[Scenario #1](https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md#scenario-1-keep-data-secret-from-the-database-administrator) seems to be more suitable.

If you want to make it more secure, you can pass the secret to the server right after its startup, so the secret is only kept in memory. It should prevent any attacker to access the secret unless they have direct access to the process memory.

I find the "scenario 1" to be sufficient for self-hosting users and the "in memory secret" option to be good enough for a service like wallabag.it.

**Comment by tcitworld** [comment]
I'm sorry but I fail to see how the second scenario is more suitable, since it only uses one key for all users of the instance. Moreover, I find it more complicated, since we must have a system aside wallabag to keep the data in memory.

**Comment by di72nn** [comment]
> it only uses one key for all users of the instance

The instance-wide secret can be used in conjunction with user data/secret (username or special data) to produce user-specific secrets.

> since we must have a system aside wallabag to keep the data in memory.

I have no say in it, since I have no idea how such statefulness can be implemented with PHP and Symfony.

**Comment by tcitworld** [comment]
Could you explain why the second solution is less suitable ? :)

**Comment by di72nn** [comment]
Web clients most of the time use **only** cookies to authorize themselves, which doesn't allow to start a user session (since no password provided). Also the key `must be destroyed once the user logs out`, which is hard to incorporate because of long lasting sessions that wallabag uses.
Heterogeneous access methods (web, API) complicate user sessions that are required for the "scenario 2".

One option would be to require at least one (per server start) user login with password in order to "unlock" the credentials (and store them until the server is shut down?). But users that mostly use API-clients will suffer.

Also, the scenario requires stateful storage `like temporary memory-backed session storage`, which was already mentioned as a difficulty.

**Comment by zertrin** [comment]
As said in https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md the first step is to write down a threat model you can live with. **Discussing encryption technology before having a threat model is always premature**.

> The first step is to think about your application's threat model. Ask yourself the following questions. Who will want to attack my application, and what will they get out of it? Are they trying to steal some information? Trying to alter or destroy some information? Or just trying to make the system go down so people can't access it? Then ask yourself how encryption can help combat those threats. If you're going to add encryption to your application, you should have a very clear idea of exactly which kinds of attacks it's helping to secure your application against. Once you have your threat model, think about what kinds of attacks it **does not** cover, and whether or not you should improve your threat model to include those attacks.

Thus the right questions that need to be asked and answered are:
- which kind of attacks do we want to protect from? (database stolen, PHP configuration exposed, server breached, ...)
- which actors are _assumed_ trusted or not (i.e. who are in Alice, Bob and Eve's roles) (server administrator, database administrator, user, wallabag admin, ...). Note that the same physical person can be in more than one role (for example the Wallabag admin can be the same as the server and database admin for self hosted instances, but that would not be the case for people on shared hosting who only upload via FTP or the like). Note also that even if often the server admin and the database admin are the same, this is not garanteed, I can host wallabag on one server and the database on another server if I wish.

Let me kickstart it (please feel free to correct me, that's just a quick thought):

### Actors:

If I put myself in the shoes of the people behind wallabag.it I have the following model:
- Wallabag admin: not trusted
- Server admin: not trusted
- Database admin: not trusted
- User: trusted
- Network eavesdropper: not trusted

But if I put myself in the shoes of an self hosted instance's admin who doesn't share this instance with other people other than himself (or trusted parties like family):
- Wallabag admin: trusted
- Server admin: trusted
- Database admin: trusted
- User: trusted
- Network eavesdropper: not trusted

If I put myself in the shoes of a wallabag admin on a shared hosting (with only access on the FTP to upload the website and very limited access to the database. No access to the server):
- Wallabag admin: trusted
- Server admin: not trusted
- Database admin: not trusted (database admin being the one with _full_ access to the database)
- User: trusted
- Network eavesdropper: not trusted


### Attacks we want to protect us from

- Network eavesdropping: HTTPS should take care of that.
- Database get stolen/compromised by third party (via for example SQL injections, database server breach)
- rogue database admin have a peek in the database and can harvest credentials
- rogue server admin has root access and looks at the PHP and config files stored on the server and finds something useful to decrypt users credentials (for example an encryption key used and stored on disk for the whole instance).

### Attacks we don't want* to prevent
_*: meaning here: attacks too advanced, too hard to prevent or conflicting with UX requirements_

- Network eavesdropping in case of HTTP insecure access. The solution here is HTTPS.

### User experience requirements
_(not part of the threat model, but important in the decision making)_

- The user that is already logged in doesn't want to input its password too often
- The user using only API access can't input password
- The setup of any technological solution chosen here must not be complicated for the user (ideally transparent)

## What to do next

- Add/change things that I missed to the Threat model
- Move things around between the categories _"attacks we want to prevent"_ and those _"attacks we don't want to prevent"_ in order to arrive at a compromise which we can live with. (because trying to make wallabag "100%" secure may not really be a sound goal since it will imply a complicated technology choice with things like in-memory temporary key storage or the like)

### Important note

It is okay to move things from the category _"attack we want to prevent"_ to the category _"attack we don't want to prevent"_, as long as it is clearly documented in the threat model.

**A threat model doesn't have to protect from everything. The goal of a threat model is precisely to document what to secure and equivalently importantly what _not_ to secure.**

For example, in my earlier comment, I proposed mainly 2 options:

- _"Store the credentials in cleartext"_ --> equivalent to a threat model where all actors are trusted or where the only attacks we want to prevent are network eavesdropping, and the rest is in the category _"attack we don't want to prevent"_

- _"encryption of the password with an encryption key stored on the server side"_ (but not in the database) --> here the threat model assumes that the server admin is trusted, and the "rogue server admin" attack from above has been moved to the category _"attack we don't want to prevent"_

**Comment by di72nn** [comment]
*Anything in this message is stated in regards to wallabag and may not be valid in general case.*

## First approach: protect only from DB theft.

Somewhat simplistic. Basically [the scenario 1](https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md#scenario-1-keep-data-secret-from-the-database-administrator).

### Actors:

 * wallabag admin: **trusted**.
 * Server admin: **trusted**.
 * Database admin: not trusted (doesn't matter).
 * User: trusted.

The wallabag and server admins have to be trusted, otherwise all the attempts to secure data are futile. If a user can't trust these actors, the user should not use it (wallabag in general or only the feature).


### Attacks we want to protect from:

 * Database gets stolen (rogue DB admin, DB server breach, SQL injections, etc.).

### Attacks we don't want to protect from:

 * Server gets compromised: root access.
  Almost no way to protect from it.
 * Server gets compromised: wallabag/web/http user access.
  Too complicated.


### Implementation:

Store instance-wide secret in the wallabag config. Derive encryption key from the secret + some user data (so, if the DB is stolen, the attacker have to brute-force records for every user separately).


### Pros:

 * Easy to implement. Hard to screw up the implementation.
 * No changes for clients.
 * *Commonly used approach (AFAIK).*


### Cons:

 * Very limited protection: only against DB being compromised.


## Second approach.

This is a variation of [the scenario 2](https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md#scenario-2-encrypting-account-data-with-the-users-login-password).


### Actors:

 * wallabag admin: **trusted**.
 * Server admin: **trusted**.
 * Database admin: not trusted (doesn't matter).
 * User: trusted.

In this approach the wallabag and server admins are trusted to deploy valid setup, but would not have access to the private credentials.


### Attacks we want to protect from:

 * Database gets stolen (rogue DB admin, DB server breach, SQL injections, etc.).
 * Server gets breached for a short time: any access level.
  Only if the server/installation is compromised for a **short time** (the fact of breach is **detected** and the server setup is **completely restored** after the breach).

### Attacks we don't want to protect from:

 * Undetected server breach.
  An attacker can gather private credentials of users active during the exposure window.


### Implementation:

The first time user adds private data, generate a random key, encrypt the private data with the key, **store the key only on client** (e. g.: web clients can use localStorage).
The client should be able to copy the key to other devices of the same account (e. g.: show QR-code on screen).

The key should be provided (transparently for the users) by clients to the server when it is needed: for article fetching and for private data managing (add / change / remove / change the key).


### Pros:

 * Server breach allows an attacker to get only keys from users that used private data-related functionality during the exposure window. No active users during the attack - no private data leaked.
 * The key can be stored on semi-trusted devices. The key by itself gives no access to wallabag. The combination of the key, username and password gives no access to private data (server can use it only to fetch articles, but should not show data to clients).
 * The key can be changed easily (if a client provides the old key). However, the new key needs to be distributed manually.
 * No server-side protected temporary storage needed.


### Cons:

 * Clients need to adapt to this mechanism (except the client don't need the functionality).
 * May be inconvenient to distribute the key between devices.
 * If a user has only one device and resets it (clears browser data), the user loses access to the private data (not a big deal, IMO).
 * Harder to implement. Easier to make mistakes.
 * **May not be thought through.**

**Comment by j0k3r** [comment]
So, @wallabag/core which approach are we going to follow?

**Comment by tcitworld** [comment]
Approach 1 seems more suitable but I definitively lack some details of the implementation.

**Comment by di72nn** [comment]
> Approach 1 seems more suitable but I definitively lack some details of the implementation.

If you're talking about my description, I meant:
Store `system-wide key` in config, store `user-specific key` (generated randomly on user creation) for every user (in DB). Use `system-wide key + user-specific key` as key for encrypting and decrypting sensitive user data. `user-specific key` is meant to act kind of like a salt. `system-wide key + user-specific key` can be done as simple concatenation (however, there might be a better way - I'm somewhat rusty on cryptography).
BTW, does ownCloud/NextCloud use something like that?

I'm also in favor of the first approach.

**Comment by zertrin** [comment]
Indeed, however please don't implement any kind of key derivation and encryption yourself, use a proper library.

I suggest using the library [php-encryption](https://github.com/defuse/php-encryption) since it's compatible up to PHP 5.4 and doesn't seem to necessitate specific dependancies.

Reading https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md is a good start.

**Comment by j0k3r** [comment]
Ok so we all agree about [scenario 1](https://github.com/defuse/php-encryption/blob/master/docs/Tutorial.md#scenario-1-keep-data-secret-from-the-database-administrator), great!

**Comment by tcitworld** [comment]
> Store system-wide key in config, store user-specific key (generated randomly on user creation) for every user (in DB). Use system-wide key + user-specific key as key for encrypting and decrypting sensitive user data. user-specific key is meant to act kind of like a salt. system-wide key + user-specific key can be done as simple concatenation (however, there might be a better way - I'm somewhat rusty on cryptography).

FYI, our current approach doesn't make use of user-specific keys, just a global key with a server salt in a file.

> BTW, does ownCloud/NextCloud use something like that?

Yes. The model threat is here only to encrypt data stored somewhere else than on the server itself. Every user has a key stored as a file to encrypt and decrypt his content. This key is unlocked at user login. Nextcloud doesn't support anything else than regular id/password auth (others are just proxys). It's also possible for the admin to have a master key that unlocks any file.
