### ISSUE TITLE
Drop SQLite support

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2766]
All is in the title. SQLite is not nice for migrations. 🤢

- [x] Defining MySQL as the default database https://github.com/wallabag/wallabag/pull/3171
- [ ] remove SQLite build from Travis
- [ ] remove all migrations related to SQLite
- [ ] remove documentation about SQLite (in doc.wallabag.org)
- [ ] remove choice of SQLite when installating wallabag
- [ ] remove all tests related to SQLite
- [ ] communicate about dropping FULL support of SQLite in wallabag (using twitter, etc.)
- [ ] create a dumping script (in whatever language) to migrate a production running instance of wallabag from SQLite to MySQL or PostgreSQL

**Comment by tcitworld** [comment]
(officially, as it's quite handy to develop on quicky)

**Comment by Kdecherf** [comment]
As I said earlier on Twitter, SQLite is quite useful for development when you don't have any rdbms available or you don't want any local rdbms (and it's my case).

Could we simply stop supporting migrations for SQLite and add warnings saying that this engine is reserved for fresh installs in dev mode?

**Comment by j0k3r** [comment]
I agree with @Kdecherf.
We should keep SQLite because it's faster to test wallabag. But we should really warn user to not use SQLite in production mostly because we don't support migration for it.

**Comment by nicosomb** [comment]
And we need to change the default database type in parameters.yml.

**Comment by j0k3r** [comment]
Also, 3.0.0 seems to far for me about that point.

**Comment by nicosomb** [comment]
FYI, I removed the question mark in the issue title.

**Comment by tcitworld** [comment]
This means a lot.

**Comment by n00b12345** [comment]
Thanks for retaining SQLite. I'm the sole user for my setup on a raspberry pi. And SQLite is well, light on resources.

**Comment by j0k3r** [comment]
The main problem is: it's really **really** hard to generate and maintain migration scripts for SQLite.

We'll drop support for migration in the coming version. But I think we'll let user use SQLite if they want to test wallabag. But we'll definitely warn user and not recommend SQLite to be used in production

**Comment by zertrin** [comment]
What's the plan for all of us who just installed wallabag with the default option?

Because let's face it, SQLite is not only the dev-friendly option, but also a very user friendly one, it's only unfriendly for those writing migrations ^^.

I mean, normal users may not really understand this decision (what's a migration? why should I care?).

What's the transition plan for them? 

Do you have stats about the share of usage of backend (SQLite/MySQL/PostgreSQL) in order to assess the impact of such a decision on the existing user base?

**Comment by n00b12345** [comment]
Wholeheartedly agree with @zertrin here. I have installed wallabag on a raspberry pi and since I run a lot of things on it, I don't want to overburden it with a MySQL server or some other server. SQLite is preferred choice. I understand the predicament of the developers though. I these days, just import all the articles in a new installation while migrating and let wallabag create a new SQLite database afresh.

**Comment by nicosomb** [comment]
FYI, I opened #3171. 
It's a easy PR, but for now, we just want to depreciate sqlite (but keep it for tests).

**Comment by nicosomb** [comment]
🎉

**Comment by zertrin** [comment]
Hello!

Sorry to unearth this, but I feel that this issue has been closed without answering some key questions:

1) _(not answered from previous comment)_ All the wallabag users that installed it a while ago while accepting the default values are currently running the sqlite backend. Now it was said [earlier](https://github.com/wallabag/wallabag/issues/2766#issuecomment-273717148) in this thread that sqlite would only be supported for **fresh** dev installs. What's the plan then for the users previously mentionned? If and when support for sqlite migrations is effectively dropped, how do they migrate to something else than sqlite without losing everything?

2) _(not answered from previous comment)_ Do you have stats about the share of usage of backend (SQLite/MySQL/PostgreSQL) in order to assess the impact of such a decision on the existing user base?

3) Will you really? and if yes _when_ are you officially dropping sqlite support for production instance?

Until at least question 3 is answered, I suggest keeping this issue open.

**Comment by nicosomb** [comment]
> If and when support for sqlite migrations is effectively dropped, how do they migrate to something else than sqlite without losing everything?

In our last release (2.3), migrations for SQLite are also available.

> Do you have stats about the share of usage of backend (SQLite/MySQL/PostgreSQL) in order to assess the impact of such a decision on the existing user base?

We don't have stats about that. But it's not a criteria for us to drop or keep something. We can't ask each of wallabag user to have a different opinion. 
We have to made choices. Some of them can be accepted, some of them can be discussed, I can understand that. 

> Will you really? and if yes when are you officially dropping sqlite support for production instance?

We prefer say that SQLite shouldn't be used for your production instance. Because migrations for SQLite are so hard to write, really. SQLite could be a good thing, but not for production environment. 
We still use it for our tests.

**Comment by zertrin** [comment]
> In our last release (2.3), migrations for SQLite are also available.

Yes (I just upgraded today and saw it) and thanks, but that's not the question being asked 😉 The question is, until when can I expect that to be the case for future releases?

> We prefer say that SQLite shouldn't be used for your production instance. Because migrations for SQLite are so hard to write, really. SQLite could be a good thing, but not for production environment.
We still use it for our tests.

That's exactly the answer I feared, and I believe that's not nice to leave users with this answer. 

"shouldn't" isn't a clear-cut answer, and thus not very useful for users. A user want's to know if he "may", or "may not" use it. Especially if the choice can be problematic down the road, and hard to change afterwards.

If it's officially not supported for production anymore (which seems to be the case), then it should be clearly communicated and there should be a plan to migrate existing users. The next time a migration happens to be too hard to write for sqlite, existing users will not be able to upgrade and will left stranded.

Maybe I was not clear enough earlier: I am **not advocating** for keeping sqlite supported in production. 

Nevertheless, since _it was the default backend until very recently_, I assume [1] there are a lot of users on the sqlite backend currently, and there should be a migration plan for those users (i.e. some documentation on how to transfer the database to mysql or pgsql). And most importantly, some communication about the deprecation for the majority of users that only read the release announcements. (saying that mysql is now the default [in the middle of the complete changelog](https://wallabag.org/en/news/new-release-wallabag-2-3-is-there-really) is not enough: it doesn't indicate to users that sqlite should be avoided)

Moreover, on the [current documentation](https://doc.wallabag.org/en/admin/installation/installation.html), there is nothing to tell users not to use sqlite. The only text specific to it says: _"If you want to use SQLite to store your data, please put %kernel.root_dir%/../data/db/wallabag.sqlite for the database_path parameter during installation."_

The answers in this thread only seem to care about developers or new users... What about your existing users?

([1]: my question about the usage statistics aimed at backing this assumption with some data.)

PS: sorry if the tone seems a bit hard, but that's really not the intention, I do 💟  Wallabag and the devs ;)

**Comment by zertrin** [comment]
> We don't have stats about that. But it's not a criteria for us to drop or keep something. We can't ask each of wallabag user to have a different opinion.
> We have to made choices. Some of them can be accepted, some of them can be discussed, I can understand that.

I forgot to address this: this is a valid and understandable opinion, but it doesn't concern the issue I am trying to discuss here.

Yes developers can decide to drop sqlite regardless of what your users want if it makes the development easier, that is your choice and it is perfectly OK. 

But assuming 90% of the existing users just chose the default rdbms before 2.3.0 and are thus currently using sqlite, if you don't help them migrate, this could lead to a very big number of opened issues here at the time something is implemented without a sqlite migration.

(and if the answer is: "for the time being we do provide sqlite migrations", once again, that's not the point. This issue is about dropping sqlite, if your argument is that you continue to provide migrations then in reality it means that you have not dropped sqlite ^^ My whole argumentation assumes that sqlite support is dropped _at some point in the future_, and that existing installations will need to migrate)

In the end, it boils down to: either sqlite is dropped or it is not but it can't be in a Schrödinger's 🐈 state (for users).

**Comment by j0k3r** [comment]
@zertrin I do understand what you said. Maybe we were so pissed off about SQLite that we went too fast in removing it.
SQLite will be support until 2.4.0 (which means every patch release of 2.3.x).
I've added a list of things to do before dropping SQLite (and releasing 2.4.0).
Don't ask for an ETA about 2.4.0 :slightly_smiling_face:

**Comment by shtrom** [comment]
For reference, I migrated my instance from SQLite to MySQL, and it was relatively painful to write a script to convert the SQL dumps.

I ended up exporting all the entries, and re-importing it into the MySQL-backed instance, which worked fairly well. I lost the tagging rules and had to recreate them manually, though (I think I had so few of them, though, that I just hacked the SQL from SQLite so it would import cleanly into MySQL).

**Comment by j0k3r** [comment]
So after some discussion, we'll keep SQLite in 2.4.0.
All current migration have been implemented and tested with SQLite.
I guess we were really pissed off with SQLite when we created this issue and I think it might be a good idea to remove it.

Also, we do not recommend to use it in production (a raspberry pi is not a production env for me).
It should be used only in edge environment, like a lightweight system (ie: a raspberry).

Finally changing the default database to MySQL might help to prevent this.

**Comment by zertrin** [comment]
> 
> 
> I managed to create a small script to handle the migration from SQLite to MySQL but I'm stuck trying to handle the migration to PostgreSQL.

@Kdecherf Sorry to dig up this from the grave, but did you publish your script somewhere? I'd like to convert my existing SQLite database to either MySQL or PGSQL. 

I tried to see if there was some doc or an issue discussing this, but couldn't find anything. 

Do you think I should open a new issue for this `SQLite -> {My,PG}SQL` topic (feature/documentation request)?

**Comment by Kdecherf** [comment]
@zertrin no I didn't put these scripts somewhere, sorry.

A full export feature may be far easier than handling these database migrations, thoughts @wallabag/core?

**Comment by j0k3r** [comment]
You can already export almost everything (+ tagging rules in the upcoming 2.4)

**Comment by zertrin** [comment]
Actually, that's something that is not well explained on the [documentation for import/export of wallabag v2](https://doc.wallabag.org/en/user/import/wallabagv2.html). When I do the JSON export, what is included, and more importantly what is **not** included.

I am opening a separate issue to discuss this further 😉

**Comment by schlamar** [comment]
So what's the current state of SQLite support now? According to https://github.com/wallabag/wallabag/issues/2766#issuecomment-490918115 it is still supported in 2.4, according to the [documentation](https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting) support is dropped?!

In my personal experience with SQLite I would say, that if you have a good database structure, you want to migrate to another good db structure and you have proper tests for database migrations, SQLite isn't **that** hard to handle. There are other projects with far more database complexity handling SQLite pretty well AFAIS, just have a look at: https://github.com/grocy/grocy/tree/master/migrations

Simple deployments should always be an important point for small self hosted applications.
