### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#2793]
Some links are broken, due to new wallabag.org website. Need to update them.

**Comment by TheNomad11** [comment]
The whole documentation is a nightmare. Needs a total rewrite that is also understandable for non-übergeeks.  Many steps missing. Assuming too much from users

**Comment by TheNomad11** [comment]
Here is a good start. Very well explained: https://got-tty.org/installation-von-wallabag-auf-debian-jessie
Works for Ubuntu 14.04 as well. Small changes needed like:

chown -R www-data:www-data /var/www/html/wallabag/var
chown -R www-data:www-data /var/www/html/wallabag/bin
chown -R www-data:www-data /var/www/html/wallabag/app/config
chown -R www-data:www-data /var/www/html/wallabag/vendor
chown -R www-data:www-data /var/www/html/wallabag/data/

In my case database host in parameters-file needs to be localhost instead of 127.0.0.1 as my Wallbag instance is hosted at a VPS.

For getting rewrite with https to work you have to set AllowOverride All in ssl apache config that was created by letsencrypt

**Comment by lapineige** [comment]
Also 2.2 and 2.3 version of the doc still show `wallabag 2.1.0` in their main title (for instance: http://doc.wallabag.org/en/2.3/).
(which is really confusing when you're searching for upgrade instructions ^^)
