### ISSUE TITLE
Composer sucking over 2G of RAM

### ISSUE THREAD

**Issue by ghost** [wallabag/wallabag#2900]
Was doing an upgrade from 2.0.8 to 2.1.1.
Stuck at "Resolving dependencies through SAT" for a long time.

Composer dependency updates are taking a VERY long time (15+ min) before it dies. With the feedback disabled, this is very concerning. Couldn't tell if it finished successfully or not.  It had failed.

Had 2 issues:
* Appears that the default composer cache location isn't writable in my host.  Perhaps there is a way to cache inside the www-data directories? 
* Only gave the VM 2G of RAM - composer ate all that and died. Stuck at "Resolving dependencies through SAT".  Had to add another Gig for the composer to finish. 

Generally, the VM only needs 512MB to run well, so needing 3G to update is a hardship, if this was on a paid host.

**Comment by nicosomb** [comment]
About composer cache dir, you can have a look to https://getcomposer.org/doc/03-cli.md#composer-cache-dir

**Comment by nicosomb** [comment]
We know that composer needs memory ... it's more a composer issue than a wallabag one.

**Comment by TheFu** [comment]
You know that composer needs RAM, but do average admins who may install/upgrade wallabag?  I didn't, but I'm just 1 guy.  Wallabag is the only use of composer on any of my systems, at least that I know about, so a little knowledge about the RAM needed to handle the dependency tree could be in order.  Up to you.

The upgrade could provide a warning that less than 2GB may not work? Could also create a temporary COMPOSER_CACHE_DIR if the default location isn't writeable.

I'm happy to provide a pull request (though it would be my first, anywhere). Will take a few days, but think it would be about 2 hrs of my effort.  Been about 15 yrs since I did any Makefile work, but it looks like a simple bash script gets the call.

**Comment by j0k3r** [comment]
This'll be fixed in the 2.4.0, see https://github.com/wallabag/wallabag/pull/3985
