### ISSUE TITLE
Import Instapaper CSV with additional information

### ISSUE THREAD

**Issue by Zlitus** [wallabag/wallabag#2946]
Actually when I import a Instapaper CSV, I can import only the URL. I want also import if the article is already archived or not and if we have some tags on it.

**Comment by j0k3r** [comment]
Could you please give more information? It is not clear to me what we should to with "additional information".
Also, please don't remove the whole default template from the issue creation form, it helps us identify which version you are using, on what you are using, etc. Otherwise we need to ask extra information like I did right now.

**Comment by nicosomb** [comment]
@Zlitus today, our Instapaper import system only gets the URL, because Instapaper only exports URL. 
If you want a specific CSV parser, you need to create a new one (by extending the Instapaper one maybe).
