### ISSUE TITLE
Preventing Importing Process from Pocket from Aborting

### ISSUE THREAD

**Issue by FaPrivatliv** [wallabag/wallabag#2983]
### Issue details

Importing from Pocket aborts prematurely and I need to restart the process. I have to repeatedly restart the process and end up with multiple duplicates.

### Environment

* wallabag version (or git revision) that exhibits the issue: V.2.2.1
* How did you install wallabag? Via `git clone` or by downloading the package? Softaculous script
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 5.6
* OS: Linux
* type of hosting (shared or dedicated): Shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

1) Click "Import"
2) Under "Pocket," select "Import Content."
3) Wait for timeout error
4) Review imported content and begin deleting duplicates.

**Comment by j0k3r** [comment]
Did you enable async import?

**Comment by FaPrivatliv** [comment]
I'm sure I didn't. How do I do that?

**Comment by j0k3r** [comment]
The Pocket import without async will work if you don't have soo much article in it. Otherwise it might timeout during import.
If you are using the async way, it'll put every article in a queue before fetching them, avoiding time out.

I don't know to configure rabbitmq or redis on a shared hosting, it depends on your provider, etc ...

**Comment by tcitworld** [comment]
You'll probably won't be able to use redis or rabbitmq on a shared hosting plan. Closing.
