### ISSUE TITLE
[BUG] Estimated reading time not shown on Material theme, list view

### ISSUE THREAD

**Issue by cosimosimeoneTR** [wallabag/wallabag#3010]
As from subject... :-)

**Comment by j0k3r** [comment]
Yeah great, the whole issue description is on the subject. Sounds nice.
What about "my computer doesn't work" too? I guess it'll be a simple issue to fix since the description is that short.
What about "I don't see the image", also an easy to fix. Don't you think?

We've defined a template for issue.
If we have done that it's because we need information from the user to be able to qualify the issue. If people remove it, this means we'll have to take some time (like I did right now) to ask few questions to determine the problem. These questions that can be answered using the damn template issue.

So, could you please add more information to your issue by following the template?
Because I can simply answer "it works for me" and close your issue.
Thanks.

**Comment by cosimosimeoneTR** [comment]
Hey Mate!
Just wanted to help, and i don't really think you would have needed **that** much more information to realize you have an issue.
Sorry for bothering you trying to help you fix a bug. :-)
Good luck! :-)
