### ISSUE TITLE
bulk tagging, marking as read, delete

### ISSUE THREAD

**Issue by leolivier** [wallabag/wallabag#3118]
Not an issue, a feature request: please add a bulk delete feature. 
I'm using wallabag hosted on a RPI2s and I have now around 500 articles saved, 300 of them are read and I would like to delete a lot of them but all I found is delete them one by one...

Furthermore, I think that a "list" layout would help this kind of feature (mark read or delete in bulk)
(maybe I'm not the first one to ask this...)

- [x] tagging
- [x] marking as read
- [x] delete

**Comment by j0k3r** [comment]
In the config menu, you'll find under the User Information tab few links to remove articles / tags / annotations.
Is it what you are looking for?

**Comment by leolivier** [comment]
Hi j0k3r,
Actually I was using version 2.1.1 which didn't have the links so I migrated to 2.2.2 (and I had a haaaard time to get it working, why I took such a long time for answering), so now I can see the links but unfortunately, no, this is not what I'm looking for:
- I don't want to clean **all** my articles, I keep a lot of them as in an archive...
- What I would like is being able to select **a lot** of items at once (but not all) and be able to delete them or mark them read.
- That's why I suggested to provide a kind of list layout (as you can see in most file explorers where you can choose to display the files either as big icons, small icons, detailed lists, ...). If I have a list, then I can quickly chose in this list (by ticking a checkbox in front of each item) the articles I want to delete or mark as read (all at once)

**Comment by leolivier** [comment]
Actually, I discovered that in latest versions of wallabag, the list layout already exist so you'd "just" have to add a column on the left allowing to select several items and some action buttons applying to the selected items.

Also, I migrated from sqlite to mysql, trying to get more performance on my RPI2 (not really better, ...) and I used phpmyadmin to achieve what I needed, ie I looked at the wallabag_entry table and ticked all the rows I wanted to delete and deleted them all at once...

**Comment by pVesian** [comment]
Hi, could the title please be edited to reflect all 3 bulk operations (tagging, marking as read, delete)? It would make the search really easier. Thanks!

**Comment by leolivier** [comment]
@pVesian : done!

**Comment by Strubbl** [comment]
was just requested in the forum, too: https://community.wallabag.org/t/howto-to-delete-more-or-all-articles-at-once/89

**Comment by Kdecherf** [comment]
Pretty cool @eriteric,

Thumb up for the modern one, but I don't think that icons on the first item are intuitive. I guess we should put these icons in the top bar like in the checkbox example.

Ping @wallabag/core @notabene @gnppn @romu70

**Comment by Kdecherf** [comment]
Also the modern one may be more intuitive on the grid view than checkboxes

**Comment by gnppn** [comment]
That's already a great execution!

Agreed, the modern one (with colored backgroundà is better, but the icons should be placed on a dedicated row or next to the top ones, with a seperator.

Imho, the grid view + Ajax loading from Pocket for bulk selections is still the best way to go. I'd like to be able to select then load more entries to select. It's what I usually did with Pocket.

**Comment by romu70** [comment]
Thanks for the ping @Kdecherf. I'm working (even if very slowly, I confess) on the new UI and interactions for wallabag. Indeed, my first wireframes are very similar to this. I find the "background color as selector" a very clever idea. Congrats ! Even if one may find checkboxes more obvious.

Regarding buttons, I totally agree,  button should have a label...and perhaps an icon. But not the opposite. An icon alone is too ambiguous and leads to errors. 

I hope to be able to show something in the coming days, but I'll keep an eye on this thread.

**Comment by romu70** [comment]
Dunno yet sir. Currently, I'm just playing with a new navigation model and low fidelity prototype. You can check out the [design](https://github.com/wallabag/design) repository to follow...and participate to this work.

**Comment by dmhowcroft** [comment]
Are we likely to get bulk editing any time soon? I'd like to bulk delete articles that got added many, many times (I think this is a glitch with the Android app?) and manage other changes (mark as read, etc).

**Comment by Strubbl** [comment]
@dmhowcroft if you have any more details to the android glitch, please open an issue https://github.com/wallabag/android-app

**Comment by petrk94** [comment]
Hello,
Im recently got really pissed off from Pocket and think about moving to Wallabag, as they changed the layout that bad way, that a effective bulk opening and deleting is not longer possible.
So Wallabag has the same issue that bulk deleting by clicking the articles is not possible?

**Comment by ei-ke** [comment]
I've recently switched from Pocket to Wallabag and hat to sort out many articles. As a workaround I set the entries per page to 300 and saved the source of the shown website. Then I used sed to create a list of clickable links which I then just opened in my browser.
Of course no automation, but less pain than moving the mouse a bit to get the trashbin shown and confirm the deletion.

`grep delete src.html | sed -e 's/^.*"\/delete\//<a href="https:\/\/YOUR.DOMAIN.TLD\/delete\//' | sed -e 's/<i.*/LINK<\/a><br>/' > out.html
`

**Comment by ManuelFte** [comment]
It's going to be 3 years of this, are there any news on whether these features at least planned? Bulk actions are essential for any service based around the storage and management of numerous elements; especially when someone has just migrated hundreds of entries from other services that are now awaiting organization. Doing it one by one is just infeasible.

**Comment by nicosomb** [comment]
It’s going to be 3 years, and?

You can look for wallabag alternatives if you want.

**Comment by feutl** [comment]
> You can look for wallabag alternatives if you want.

That's the spirit 👍

**Comment by j0k3r** [comment]
Or you can help us improve that part too.
Feel free to open a PR to enable bulk tagging.

**Comment by feutl** [comment]
> Or you can help us improve that part too.
> Feel free to open a PR to enable bulk tagging.
This is the best statement I get on github and others all the time, but no, not everyone is a programmer and/or wants to get one.
Anyhow, I paid for the service on wallabag.it but the support and feedback experience (including this issue here) was not very promising to be honest.

**Comment by ManuelFte** [comment]
> This is the best statement I get on github and others all the time, but no, not everyone is a programmer and/or wants to get one.
> Anyhow, I paid for the service on wallabag.it but the support and feedback experience (including this issue here) was not very promising to be honest.

Indeed. It's very disappointing when open source projects, which you expect to be welcoming communities as they're based around the spirit of collaboration, turn out to not really care about their community and you're met with sarcastic, mocking, disinterested, or plainly rude answers whenever you attempt to give feedback or get support.

I'd have considered submitting a PR (despite the fact that my schedule makes it difficult) or to help in some other way if I was told how I could, but the attitude I see here certainly doesn't encourage you to contribute or to even stay around.

I'm going to save @nicosomb's reply as a prime example of how not to treat your community. 👍

**Comment by dmhowcroft** [comment]
I understand that there are limited person-hours to work on this project, and I am grateful for the functionality it *does* have, but bulk editing seems like one of the most basic features for an archival tool like this to have, and I'm sad that it still isn't implemented.

**Comment by anarcat** [comment]
> Anyhow, I paid for the service on wallabag.it but the support and feedback experience (including this issue here) was not very promising to be honest.

> Indeed. It's very disappointing when open source projects, which you expect to be welcoming communities as they're based around the spirit of collaboration, turn out to not really care about their community and you're met with sarcastic, mocking, disinterested, or plainly rude answers whenever you attempt to give feedback or get support.
>
> I'd have considered submitting a PR (despite the fact that my schedule makes it difficult) or to help in some other way if I was told how I could, but the attitude I see here certainly doesn't encourage you to contribute or to even stay around.

> I understand that there are limited person-hours to work on this project, and I am grateful for the functionality it does have, but bulk editing seems like one of the most basic features for an archival tool like this to have, and I'm sad that it still isn't implemented.

Look here. I'm a user of wallabag, and also a developer (I wrote wallabako). And I totally understand where those guys are coming from. You can't come into a free software project, ran by volunteers, that you get for free, and just say "this should be your priority because it's a basic feature" or "this has been waiting for too long".

That's not how free software works.

If you want to get this feature developed, hire a consultant, discuss the spec, and get it done. You'll have your precious feature, devs will have food on the table, and the entire community will benefit.

And yes, you may be a paying customer of wallabag.it. But really, how much of that money do you think goes to developing wallabag itself? At 25EUR/mth? I'd bet there's probably zero and that just covers hosting and sysadmin costs.

I am here to say I am really happy that the wallabag developers are giving me their time. And I understand why this feature hasn't been developed: it's because it's hard, and maybe none of the wallabag developers directly feel a need for it.

People need to understand that nothing is free in this world. You might want to go with Pocket, Evernote, or whatever if you want a "free" product. But you need to understand there are serious downsides to those projects. For one, you won't even *get* a forum like this where you can ask for features. And of course, because it's free, you're the product and your entire browsing history is tracked and snitched.

So, you know, I'd be careful about pushing those devs around. It's really demotivating for volunteers when they're told that the free work they're giving is not good enough. I know some people leave because of that, and we don't want that to happen, do we? :)

So, please, let's just take a deep breath and move on. If someone has patches for this, they'll send them. Otherwise bullying devs to work on this is just counter productive, trust me. ;)

**Comment by ManuelFte** [comment]
I don't believe anyone here was "pushing the devs around". The fact that you see something being requested by multiple people for years is not "pushing", it's a reflection of the community needs; and no one has done it in an inappropriate or disrespectful manner either. There's nothing wrong with explaining what you think a product is lacking and why you believe it'd be a valuable addition. I see even people proposing drafts on how this could be implemented. It's also all but natural to wonder what's the state of the request after you see it has been unaddressed for a long time. The community has done nothing bad here and one shouldn't pretend to put blame on them for merely giving feedback.

We do all understand that open source projects are developed by busy people during their free time and that they're usually lacking in money and manpower; but this is sometimes used as pretext to feel free to give outright bad support, "you don't pay us, you have no right to say anything".

There are multiple good ways to handle these issues. There's Bountysource for users interested in funding their favorite requests. You can post a notice looking for volunteer developers to target specific projects. You can implement a voting system to tackle the most popular issues first. But what's inexcusable is to just give answers like _the lead developer_ of this project did, "And? Go away if you don't like it".

This is not how you put the community to your side or motivate people to collaborate with your project. Being welcoming and supportive with your users and showing interest and openness to feedback is basic in any service, and even more in the open source community. If suggestions are going to be labeled as "pushing" and requests are going to be dismissed with rudeness and asked to be content or leave, then you may just not have forum at all.

**Comment by dmhowcroft** [comment]
@ManuelFte posted to ask for an update and highlight why he thinks this is an important feature and @nicosomb responded by telling him to take a hike. Maybe @ManuelFte could have phrased his request better, but @nicosomb seems to have replied in a disproportionately rude way.

How are we supposed to bump an issue we find important or ask for an update in the future so that we don't trigger a dismissive response?

**Comment by thibaultamartin** [comment]
I understand it can be exasperating to see an issue stalled. But Libre software such as this one, when it's not backed by a company, is not a traditional product you're buying with paid support. See it more like a the toy of the developpers, and you can get a copy for free :)

> We do all understand that open source projects are developed by busy people during their free time and that they're usually lacking in money and manpower; but this is sometimes used as pretext to feel free to give outright bad support, "you don't pay us, you have no right to say anything".

I think the point is not "you have no right to say anything" but as @j0k3r says "if you can do it or find someone to do it, please do it and we'll review it to upstream your efforts". The developers on Wallabag work on their free time: they don't necessarily want to build the best product. They want to work on things they enjoy or on things that solve their very own problems.

> There's Bountysource for users interested in funding their favorite requests.

This is an interesting point, but unless you reach not only a large audience, but a large audience willing to pay, you likely won't have enough funds to pay a developper the minimum wage to work on an issue. Funding Libre software is a real issue.

> You can post a notice looking for volunteer developers to target specific projects

That's more or less what this issue is about :)

> You can implement a voting system to tackle the most popular issues first.

This is what I'm talking about a bit earlier in my comment: this may not be what the developers of the project want. They may not enjoy working on the most demanded issues, and they have the right to spend time on things they like. It's free time they're giving away after all

> Maybe @ManuelFte could have phrased his request better, but @nicosomb seems to have replied in a disproportionately rude way.

I think @dmhowcroft and @anarcat got it right. Let's not escalate it any further. Maybe @ManuelFte sounded more pressuring than he intended it, maybe @nicosomb overreacted. Let's not forget that everyone here either codes for free or reports issues for free, and nobody owes nobody anything.

**Comment by nicosomb** [comment]
> There's Bountysource for users interested in funding their favorite requests.

And most of the time, it's not a funding problem. It's a time one.

**Comment by ei-ke** [comment]
@nicosomb @j0k3r I've no programing knowledge. Just tinkering stuff together here and there. I doubt I can add this feature and have no clue how hard this is to implement, but probably you do.
If it's something that needs to be implemented in 2-3 files could you maybe let me know where I would need to start?
And sorry for adding my workaround that started this discussion -.-

**Comment by anarcat** [comment]
> How are we supposed to bump an issue we find important or ask for an update in the future so that we don't trigger a dismissive response?

There are various mechanisms. The one I would suggest is the :+1: sign that you can easily click on the top of the issue. Those things are not just silly smileys to make GitHub look good: they are real indicators of the popularity of an issue or feature request. People can use those parameters to sort the issue queue and prioritize.

GitHub used to not have those flags, and issues queues were a mess of "bump" like those you are suggesting. They were noisy and annoying for everyone involved, because everyone would get a ping all the time.

(@ManuelFte suggested to implement a voting system on issues: this is what those flags do. That system already exists! :)

----

Part of my *own* irritation with the situation here is exactly that: I get pinged for that issue, which I also care about, while there's no progress on it. It's just noise in my inbox, and I'm not even a dev on that project. 

I understand just hitting that :+1: might not be as satisfactory as bumping with a comment. The former is a silent vote, the latter is noisy. Everyone registered on GitHub has the power to bump issues like this and ring tens if not hundreds of people when they do. With such great power should come great responsability. The anniversary of an issue, for me, is not a good measure of why an issue should be pinged.

The only reason I ping issues like this is to remind devs *if* they had set a timeline. I did so in another project where they said they'd make a new release in (say) "three months". After the three months delay, naturally, nothing had happened, so I gently pinged the issue, offering my help with the release process. The dev was okay with the reminder, because they *had* set a timeline. But if they miss it again, I won't bug them, because it will show they're unlikely to have the time to respond.

I hope that helps!

**Comment by j0k3r** [comment]
Thanks everyone to be part of that discussion.
I suggest that we don’t comment anymore about that (over) reaction / free time, etc.

Let’s keep focused on the issue itself.
If people still want to debate about that our Gitter is open.

To talk about the issue, we do not have plans to work on it at the moment. We are mainly focused on the 2.4.0 release after month without a single release.

**Comment by nicosomb** [comment]
What do you think about this video? 

It's available on https://app.wallabag.it and soon on wallabag.

![tuto-mass](https://user-images.githubusercontent.com/121870/78499782-f7677e80-7752-11ea-9e38-900a7c543d71.gif)

**Comment by anarcat** [comment]
would love to have ways to add (or even remove!) tags to articles too, but that's a great start!

**Comment by gnppn** [comment]
I was so happy to see your tweet about this!

This is a great start. Personnally, I'd follow the Pocket example (I know) by letting people select by clicking anywhere on the entry block. That'd be much easier to select.

Pocket does that differenciating the normal usage and the bluk action mode (via a toggle button). I guess it could also be activated after the first selection.

**Comment by nicosomb** [comment]
@gnppn it's a good improvement. 

I think that I will open a pull request with bulk marking as read, favorite and delete first and then, we'll improve it (improve features and improve UI).

**Comment by petrk94** [comment]
the bulk deleting looks pretty well developed. 
How does it look with bulk opening, will a simple right click work to open the link directly or is there a way to click the original link to get opened as website and not inside wallabag?

Thanks for your hard works!

**Comment by romu70** [comment]
IMHO, the solution as shown in this poc is the best. Ok, having checkboxes may be not the sexiest solution, but it prevents users to have to think about how the product works. It's pretty straightforward for everybody. 

And this also makes the basic wallabag use case straightforward. Click on the checkbox to select, click on a text zone to open the article. Direct, simple.

**Comment by nicosomb** [comment]
@petrk94 hello! thank you for your post. About your idea to open many links, it's not planned. Sorry!

**Comment by petrk94** [comment]
@nicosomb,
maybe I explained it not good enough. I dont mean to mark all elements and open at once.
I mean, that every saved element shows up a link of the original source, so while I can select each element manually, I want to be able to click on the original source, because this is what Pocket has removed and this is bothering my work flow, I want open the source and remove it from pocket as its not longer required etc.

Is this really not possible?

**Comment by Kdecherf** [comment]
Hello there,

I made several quick and dirty patches for my instance, adding several mass actions.

Here is a proposal for the mass tagging:

![2021-04-28-111402_641x86](https://user-images.githubusercontent.com/226063/116379224-1a0f7e00-a813-11eb-877f-9c6d5a58585e.png)

The tag button is the last one and there's an input field next to it to type tags to add and/or remove (_on my instance I can remove tags by prefixing them with a dash_).

I also added a button to mass download, it let me export specific articles of the current page in an epub file. Don't know if it would be profitable for the community.

@wallabag/core do you find it acceptable?

**Comment by romu70** [comment]
Good job! I missed the ability to massively assign tags, this is exactly what I need! And this sounds totally consistent with what has been done so far for bulk actions.
April 28, 2021 11:22 AM, "Kevin Decherf" ***@***.*** ***@***.******@***.***>)> wrote:
	Hello there, 

	I made several quick and dirty patches for my instance, adding several mass actions. 

	Here is a proposal for the mass tagging: 

	 (https://user-images.githubusercontent.com/226063/116379224-1a0f7e00-a813-11eb-877f-9c6d5a58585e.png) 

	The tag button is the last one and there's an input field next to it to type tags to add and/or remove (on my instance I can remove tags by prefixing them with a dash). 

	I also added a button to mass download, it let me export specific articles of the current page in an epub file. Don't know if it would be profitable for the community. 

	@wallabag/core (https://github.com/orgs/wallabag/teams/core) do you find it acceptable?

**Comment by petrk94** [comment]
@Kdecherf looks nice!

**Comment by anarcat** [comment]
that looks great! it would also be great if we could get autocompletion on the tag name, i have a tag proliferation problem and it's partly due to the web app not auto-completing those... but i guess that's a different problem. :)

**Comment by Kdecherf** [comment]
@anarcat yeah, there's a dedicated issue for the autocompletion request: #1869

**Comment by Kdecherf** [comment]
@nicosomb not yet, I'll try to open a draft PR in the coming days.

**Comment by helmut72** [comment]
@Kdecherf Any news about this PR? Bulk tagging is one of the few features I miss a lot.

**Comment by Kdecherf** [comment]
@helmut72 I've just opened a PR which is available here: https://github.com/wallabag/wallabag/pull/5838

Thanks for the reminder :sweat_smile:

**Comment by helmut72** [comment]
@Kdecherf  Thanks for the PR 👍
