### ISSUE TITLE
medium.com articles with alternate domain not fetched

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#3218]
### Issue details

Content from articles from medium.com are usually fetched properly. But if an article is hosted on medium.com CMS, but on a different domain, content does not get fetched. E.g.:
* https://hueniverse.com/oauth-2-0-and-the-road-to-hell-8eec45921529
* https://42hire.com/how-to-answer-the-whats-your-current-salary-job-interview-question-486254cb59ad
* https://m.subbu.org/dont-build-private-clouds-9a54b3d30c8b
* https://medium.freecodecamp.com/so-yeah-we-tried-slack-and-we-deeply-regretted-it-391bcc714c81
Instead of the content being fetched, wallabag gets redirected to the medium startpage, which's content gets fetched then. 

### Environment

* wallabag version (or git revision) that exhibits the issue:2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable):-
* php version:
* OS:debian
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):mysql

### Steps to reproduce/test case

- add https://hueniverse.com/oauth-2-0-and-the-road-to-hell-8eec45921529
- go that article in wallabag and see medium startpage has been fetched

**Comment by j0k3r** [comment]
Well, after checking multiple issues about site config from you, it seems that every time it works great on the 2.3 and 2.2.3.
Could you please check (I don't know what) your instance? Because it seems more to come from your instance than from wallabag it self.

![image](https://user-images.githubusercontent.com/62333/27261470-e42adb80-5443-11e7-8067-5d72832a6672.png)

**Comment by Strubbl** [comment]
Thank you. My instance had a problem.
