### ISSUE TITLE
Tagging rules tag wrong articles

### ISSUE THREAD

**Issue by rfc2119** [wallabag/wallabag#3310]
I had a tagging rule like this:
> if « content matches "OpenAI" OR **content matches** "Artificial Intelligence" » then tag as « AI » 

then I updated it like this:

> if « content matches "OpenAI" OR "Artificial Intelligence" » then tag as « AI »

I did that for a couple of rules, in which there exists a common element. The result was every new article I add gets tag by the modified tag rule. Here for example, it's "AI".

Reverting the rules back solves the problem.

Version 2.2.3 on Ubuntu 16.04 with Nginx on localhost. Running php7.0

**Comment by nclsHart** [comment]
As I understand the rule engine, your rule is not interpreted as you are expecting.

> if « content matches "OpenAI" OR "Artificial Intelligence" » then tag as « AI »

is interpreted as : 

> if « content matches "OpenAI" OR **TRUE** » then tag as « AI »

because the right part of the OR operator does not have operator. So, your rule is always true.

The correct way for doing this should be:

>  if « content matches ["OpenAI", "Artificial Intelligence"] » then tag as « AI »

But for the moment the `matches` operator does not support the array notation.

**Comment by EgyptBeast** [comment]
It is indeed as you described. I wanted to **group** similar keywords into one conditional statement.

I'll leave this issue for now for the devs to close it or mark it as a bug (or a feature?).
