### ISSUE TITLE
Some pages are fetched incompletelly

### ISSUE THREAD

**Issue by eemantsal** [wallabag/wallabag#3349]
When saving some pages, very frequently, I'd say more than 25% of times, some images are missing, or even some text and links. I think that a couple of examples are explanatory enough, although I suppose you'll get a better idea by visiting the links and verifying the infromation loss when saving to Wallabag:

Here, Wallabag misses all the section titles and links in those titles:
http://www.symphozik.info/schumann-analyse-des-dichterliebe-les-amours-du-poete,107,dossier.html

**The original page**:

![captura_20170915_222251](https://user-images.githubusercontent.com/18057272/30502807-199f3d5a-9a68-11e7-82b6-ad553e154bd2.jpeg)

**The saved one**:

![captura_20170915_222404](https://user-images.githubusercontent.com/18057272/30502159-5ca76328-9a65-11e7-8834-47c3e7057275.png)

Here, it misses all the photos except one:
https://www.muyinteresante.es/ciencia/fotos/10-trucos-para-mantener-tu-cerebro-en-forma/evita-los-complementos-alimenticios

**Original**:

![captura_20170915_222730](https://user-images.githubusercontent.com/18057272/30503181-9a0de562-9a69-11e7-991c-7314ce565f48.png)

**Saved**:

![captura_20170915_222815](https://user-images.githubusercontent.com/18057272/30502187-7afdbeee-9a65-11e7-802f-1fc9c8810718.png)

Telegram's Instant view works awesomely well, even better than Firefox's reader view. It doesn't work for every site but for those where it works there are almost no mistakes ever. As Telegram is GPL licensed perhaps you could "steal" some bits of code to improve Wallabag's web importing engine? Just speculating.

I'm using Wallabag from https://framabag.org

**Comment by karietta** [comment]
Hello.
Framabag user too, I have experienced the same issue for months.
Even thumbnails lack images.
I sent an e-mail about this problem at hello@wallabag.org but never received any answer.
Is this problem linked to my framabage user status or is this a bug?
Will I have an answer here, pleeeeaaaaase??

![sans titre](https://user-images.githubusercontent.com/37737913/37863828-050db668-2f65-11e8-81cc-88834cdbbc6b.png)

**Comment by HolgerAusB** [comment]
Hi, @eemantsal,

The issue is very old but I wrote new config files.
- framabag doesn't offer wallabag any longer :-( are you still with wallabag?
- symphozik.info is fixed
- muyinteresante.es now redirects to muyinteresante.com, but I can't find the article you named. But with my config it should work. Example: https://www.muyinteresante.com/historia/7-sucesos-historicos-que-ocurrieron-en-halloween.html

Hi @ghost,

if you still have problems with a different hoster, please open a new issue and provide links to articles.

@ Both:
Please use one issue per domain. Don't mix domains in the same issue.
