### ISSUE TITLE
Using the API to add articles

### ISSUE THREAD

**Issue by csgnyc** [wallabag/wallabag#3352]
I've been fooling around with the API.  I can now get access tokens and use those tokens to get all articles using `curl "http://MYWALLABAG:PORT/api/entries.html?access_token=MYTOKEN"`

The problem is I now want to add articles (in this case, I'm adding Google News).  Using models I've found in various places, I've tried
`curl "http://MYWALLABAG:PORT/api/entries.json?access_token=MYTOKEN&url=news.google.com"
`What I get as a result is the same thing as the previous curl, namely, a listing (including text) of all the articles I've previously added to Wallabag, and news.google.com does not get added.

Can anyone see what I'm doing wrong?  Thanks.
### Environment

Running Wallabag through Docker on my synology using MYSQL/Maria DB.

**Comment by 4oo4** [comment]
You may want to look at the API reference some more. Because you don't specify an HTTP method, curl is defaulting to `GET` so, when you do `curl -X GET http://MYWALLABAG:PORT/api/entries.json`, you're asking it to return a list of the existing. See `/wallabag/web/api/doc` on your server to show all of the API methods.

![selection_003](https://user-images.githubusercontent.com/15698835/30523691-61acd816-9bab-11e7-980f-8009d065265c.png)

What you want is to is a `POST` with `curl` instead (use `-X` to specify a method other than `GET`), which will create an entry like you're looking to do:
![image](https://user-images.githubusercontent.com/15698835/30523673-3989e4f0-9bab-11e7-9673-c09a501599d5.png)

See: https://v2.wallabag.org/api/doc (Note - they're having issues with HSTS right now, so you'll have to use Google's cache to view it, or you can view it here: https://github.com/wallabag/doc/tree/master/en/developer/api)

When messing with the API, using HTTPie like they suggest also makes it a lot easier if you're not too familiar with `curl` :wink:

**Comment by csgnyc** [comment]
Thanks, @4oo4.  I had just realized the same thing.  I used this format instead (which seems different from what I've seen on the web) and it worked.  To add an article I used,
`curl  --data "access_token=ACCESSTOKEN&url=news.google.com" http://MYWALLABAG:PORT/api/entries.json`

**Comment by 4oo4** [comment]
@csgnyc Nice! Actually hadn't used `curl` with that option before, but it looks like that's doing the same thing:


> -d, --data <data>
> 
> (HTTP) Sends the specified data in a POST request to the HTTP server, in the same way that a browser does when a user has filled in an HTML form and presses the submit button. This will cause curl to pass the data to the server using the content-type application/x-www-form-urlencoded. Compare to -F, --form.
> 

https://curl.haxx.se/docs/manpage.html#-d

**Comment by nicosomb** [comment]
FYI, v2.wallabag.org is an old instance, we'll delete it in few weeks.

**Comment by 4oo4** [comment]
@nicosomb Yeah, @tcitworld mentioned that when I asked about the HSTS error, I went ahead and updated the link to the new site.

**Comment by Rurik19** [comment]
You can use my [https://github.com/Rurik19/wallabag-cli](wallabag-cli) package instead :smile:
