### ISSUE TITLE
RSS to Wallabag

### ISSUE THREAD

**Issue by mritzmann** [wallabag/wallabag#3360]
It would be great if links from an RSS feed could be imported automatically.

----

**Use case:** My RSS Reader generates an RSS feed from all articles I mark. It would be great if Wallabag would import this RSS feed automatically on a regular basis. So I could mark in my RSS feed reader all articles I want to read later and Wallabag would import them automatically.

**Comment by mritzmann** [comment]
Is there already a way to do this now?

**Comment by Findus23** [comment]
Hi,

If you really want this feature and are not against a bit of tinkering, you can look into my (unfortunately a bit chaotic) Python script which does exactly that:
https://github.com/Findus23/rss2pocket
(Don’t be confused by the name. I initially wrote it for pocket but now migrated it to wallabag

**Comment by nicosomb** [comment]
Hello @mritzmann. 

Today it's not planned to add this feature in wallabag. 

wallabag is a tool where you already selected articles (and save them to archive them or read them later). 
With a RSS feed, you don't have this "selection" part: all your articles will be saved into your wallabag account (or we can imagine an interface where you select with checkboxes the new articles to save). 

I think that the better way to handle RSS feeds is to have ... a RSS reader whih integrates wallabag. You can find some of them here: https://wallabag.org/en#rss 
Or you can use scripts like @Findus23 's one 👍

**Comment by oakbrad** [comment]
@nicosomb I would also be extremely interested in this feature

I already select the articles in my feed reader (TT-RSS) by 'starring' them. This creates a curated RSS feed. Previously with Pocket I would import that RSS feed with IFTTT.

There is a plugin for TT-RSS for Wallabag but it only works on the web interface, which I never use. Part of the appeal of TT-RSS is, like Wallabag, is there are many clients. So I can 'star' an article from any client (iOS, desktop, web) and it will appear in my custom RSS feed.

So in order to integrate with my RSS reader, I need to import the RSS feed it creates :)

@Findus23 Thank you will try your solution

**Comment by Findus23** [comment]
@oakbrad 
I hope you like my script. I just remembered that there were some changes I wanted to do for a while.

If you have any issues or ideas, just contact me.

**Comment by foxmask** [comment]
otherwise there is always https://github.com/foxmask/django-th for any RSS feeds to read/produce

**Comment by hugot** [comment]
For those using miniflux as RSS reader, I have written a small emacs package that is able to sync articles of a set of feeds between miniflux and wallabag, and keep their "read" and "unread" status in sync. I have a cronjob running this periodically somewhere. It has no dependencies other than emacs itself. I wrote this so that I could read the news on my ereader, maybe it can be of use to others as well :)

https://github.com/hugot/n2wal

**Comment by DIWesser** [comment]
I'd also be interested in this feature and don't think that exporting from Wallabag to an RSS reader can really replace what native RSS support would offer. To the best of my knowledge, there is no selfhostable or FOSS RSS reader that supports annotations and tags as well Wallabag does. Wallabag is better suited to being a place to throw all the articles I read so I can pull up something I found interesting with a single search query later on then any RSS reader out there right now.

**Comment by jpcaruana** [comment]
this works for me pretty fine: https://github.com/jpcaruana/rss2wallabag

**Comment by nicosomb** [comment]
Hi there, 

Thank you for your feature request. We, at wallabag team, really appreciate external contributions and new ideas.
But this feature is not a wanted one by the core team. 

You can for example fork wallabag (Open source spirit ❤️) or write a blog post to explain how implementing this feature. 

I wrote a blog post about that: https://wallabag.org/en/news/wallabag-wont-accept-pr-feature-request

I hope that you can understand our choices. 

Have a nice day, 

Nicolas

**Comment by 2br-2b** [comment]
I tried to look at the blog post, but it is no longer available:

![Image](https://github.com/user-attachments/assets/a0e8235b-6b1e-4ced-83f5-724e539590f8)

If only it had been archived...

(I'm just pointing out the irony - it's probably on archive.org)

**Comment by HolgerAusB** [comment]
the path changed slightly, @2br-2b 

https://wallabag.org/news/wallabag-wont-accept-pr-feature-request/

**Comment by yguedidi** [comment]
Replaced by #8907
