### ISSUE TITLE
domain / url problem in 2.3.0

### ISSUE THREAD

**Issue by prolibre** [wallabag/wallabag#3485]
Désolé mais je suis plus à l'aise en français.

Je viens de mettre à jour wallabag : aucune erreur rencontrée lors de la mise à jour mais l'interface est cassée (police non chargée, certains visuels sont inaccessibles etc.).

Je pense que le soucis vient du fait que mon installation n'est pas sur un (sous) domaine dédié : elle est de type http://www.domain.tdl/wallabag

Je pense que c'est en raison de l'ajout d'un paramètre _domain_name_.

![wallabag](https://user-images.githubusercontent.com/17174902/33876837-f0270e04-df26-11e7-887b-d403f194cb6d.png)

Au début j'avais mis http://www.domain.tdl mais j'ai aussi essayé en mettant l'url complète (modif dans parameters.yml) : http://www.domain.tdl/wallabag (aucune différence après un php bin/console cache:clear --env=prod)

Je donne un exemple de lien css/média/font inopérant 👍 
https://www.domain.tdl/fonts/MaterialIcons-Regular.ttf ( erreur 404 ) qui devrait être : 
https://www.domain.tdl/wallabag/fonts/MaterialIcons-Regular.ttf 

Sinon un grand merci pour cette version.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.0

**Comment by brotherduck** [comment]
Même problème ici, en regardant dans la log je vois qu'il n'arrive pas à trouver un certain chemin :

x.x.x.x - - [12/Dec/2017:11:07:18 +0100] "GET /wallassets/fonts/MaterialIcons-Regular.ttf HTTP/2.0" 404 324 "https://www.mondomaine.amoi/wallabag/web/wallassets/mate
rial.css" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"

Contournement temporaire : il suffit de créer un lien symbolique vers le répertoire wallawabag/web/wallassets dans le DocumentRoot Apache. Bon, c'est du bricolage mais au moins on récupère les icones.

**Comment by prolibre** [comment]
@brotherduck je viens de faire un alias dans ma config d'apache : 
Alias /wallassets /mon_dir_wallabag/web/wallassets

mais comme tu dis c'est temporaire.

J'espère que le bug sera corrigé parce qu'une fois en ligne (avec le backup des images), changer de domaine ne va pas être commode (les url des images sont stockées en dur)  ;-(

**Comment by FrenchHope** [comment]
Dans mon cas j'ai dû ajouter à ma configuration apache un

Alias /wallassets /var/www/chemin/vers/mon/wallabag/web/wallassets

**Comment by JimboJoe** [comment]
Is there any chance for this issue to get milestoned for version 2.3.1...?

**Comment by 4oo4** [comment]
Pour ceux qui utilisent nginx, il y a cette règle de `rewrite` qu'on peut ajouter pour countourner le problème:

`rewrite ^(/wallassets/)(.*)$ https://example.com/wallabag/web/wallassets/$2 permanent;`

**Comment by ngosang** [comment]
I fixed it with a symbolic link:
` ln -s wallabag/web/wallassets wallassets`

**Comment by Kdecherf** [comment]
Could you try the following fix and remove your workaround for further tests?

``` bash
sed -i 's@/wallassets/@@' web/wallassets/material.css
```

**Comment by brotherduck** [comment]
Fix doesn't work, when I do this and then remove my symbolic link the icons are broken again.

**Comment by prolibre** [comment]
@brotherduck 
it's an interim solution. Leave the symbolic link until the bug is fixed.
c'est une solution provisoire. Laissez le lien symbolique jusqu'à correction du bug.

**Comment by Kdecherf** [comment]
@brotherduck did you clear your browser cache while trying the sed fix?

**Comment by brotherduck** [comment]
I've tried again : execute sed command, remove symbolic link, clear browser cache and then reload the page. Still the same result, icons are broken.

**Comment by Kdecherf** [comment]
@prolibre peux-tu fournir la configuration du serveur web ?

@ngosang @brotherduck can you provide your webserver's configuration file? I'm trying to reproduce your issue locally

**Comment by ngosang** [comment]
Sure. Apache 2 in Linux.
Apache root path `/var/www`
Wallabag in path `/var/www/wallabag` (git clone)
Apache configuration (from wallabag documentation with some changes)
```
    <Directory /var/www/wallabag/web>
        AllowOverride None
        Order Allow,Deny
        Allow from All

        <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ app.php [QSA,L]
        </IfModule>
    </Directory>
    <Directory /var/www/wallabag/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>
```

NOTE: I think this bug can be fixed easily.
In the file https://domain.org/wallabag/web/wallassets/material.css 
you can find several absolute URLs like this `url(/wallassets/fonts/Roboto`
just remove the first slash  `url(wallassets/fonts/Roboto`

**Comment by prolibre** [comment]
@Kdecherf 

debian 9 / apache2  / PHP 7.0.19-1 / mysql  Ver 15.1 Distrib 10.1.26-MariaDB
rien de bien original.

**Entre temps j'ai changé ma configuration pour un sous domaine dédié et ça marche nickel.**

Pour ma config apache2 c'était tout simple aussi : 

```
<Directory /DIR_INSTALL/wallabag/web>
Include conf-available/maintenance.conf
Require all granted
<IfModule mod_rewrite.c>
        options -MultiViews
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ /wallabag/app.php [QSA,L]
</IfModule>
</Directory>
```

**Comment by JimboJoe** [comment]
Hello @Kdecherf , I confirm your fix doesn't work with [this configuration](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/master/conf/nginx.conf) (YunoHost package).
To fix, I have to do:
```
sed -i 's@/wallassets/@/wallabag/wallassets/@g' web/material.css
```
where `/wallabag` is the relative URL for the installation.

**Comment by Kdecherf** [comment]
Yeah @JimboJoe I failed to provide a correct sed command, sorry.

For all of you who having this issue, could you try this patch?
https://github.com/wallabag/wallabag/pull/3524

**Comment by nicosomb** [comment]
@prolibre @ngosang @brotherduck @4oo4 could you test the fix please?

**Comment by prolibre** [comment]
Sorry, but since then I have migrated my instance to a sub-domain

**Comment by 4oo4** [comment]
@nicosomb Can do, I'll try to do that this weekend.

**Comment by 4oo4** [comment]
@nicosomb That fixed it for me, thanks!

**Comment by nicosomb** [comment]
Perfect. We’ll release 2.3.1 tomorrow. 
Today I can’t 🥂🎄

**Comment by ngosang** [comment]
I'm late, but it's working for me.

**Comment by respinfo-issat** [comment]
Bonjour à tous,

après avoir cherché pendant plusieurs heures à résoudre le même problème, je pense avoir trouvé la solution (en compilant plusieurs réponses trouvées ça et là !)

##Ma configuration en place :
serveur Apache 2.4.25 sous Debian 9 avec MariaDB.
Installation "classique" de wallabag via composer dans le répertoire **/var/www/html/framabag**

virtualhost ssl (https) avec DocumentRoot /var/www/html/

Wallabag (doit être et) est accessible par **https://www.mondomaine.tld/framabag/**

Configuration définie (fichiers) :
Dans le fichier framabag/app/config/parameters.yml :
parameters:
    ...
    domain_name: 'https://www.mondomaine.tld/framabag/'

Dans le fichier default_ssl.conf (le virtualhost d'Apache) :
<IfModule mod_ssl.c>
        <VirtualHost www.mondomaine.tld:443>
                ServerAdmin mon@email.fr
                DocumentRoot /var/www/html
                ......
                Alias /framabag "/var/www/html/framabag/web/"
                <Directory "/var/www/html/framabag/web">
                        AllowOverride None
                        Order Allow,Deny
                        Allow from All
                        Require all granted
                        <IfModule mod_rewrite.c>
                                Options -MultiViews
                                RewriteEngine On
                                RewriteBase /framabag/
                                RewriteCond %{REQUEST_FILENAME} !-f
                                RewriteRule ^(.*)$ app.php [QSA,L]
                        </IfModule>
                </Directory>
                ...
        </VirtualHost>
</IfModule>

Après, dans le répertoire .../html/framabag/, exécuter  "bin/console cache:clear -e=prod"

Résultat :
* Plus de problème de /login, on a bien /framabag/login/
* Les images, css, js, etc. sont également bien atteints par le navigateur.
* Le problème de  boucle de rewrite est résolu : AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

**Comment by JialuZhang** [comment]
In your configuration,
```
    <Directory /var/www/wallabag/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>
```

the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
