### ISSUE TITLE
Web UI completely blocked with: The string to escape is not a valid UTF-8 string.

### ISSUE THREAD

**Issue by kedare** [wallabag/wallabag#3633]
### Issue details

When accessing the Wallabag web interface, instead of the actual interface, it shows

500: Internal Server Error
The string to escape is not a valid UTF-8 string.

### Environment

* wallabag version (or git revision) that exhibits the issue: Docker image wallabag/wallabag:2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? Official docker image
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP 7.1.12 (cli) (built: Dec 27 2017 14:24:15) ( NTS ) (From docker image)
* OS: Docker (Fedora host)
* type of hosting (shared or dedicated): Docker over dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Access the web interface ? I don't know exactly what could cause this, this was working fine before, I know it started after a day I added a few new pages to wallabag, maybe it's related to that ? (A page containing invalid encoding could break the whole web UI?)

When accessing the web interface showing this error (any page basically), prod.log shows this :

```
[2018-04-18 19:26:18] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"Wallabag\\CoreBundle\\Controller\\EntryController::showUnreadAction","page":1,"_route":"homepage"},"request_uri":"http://wallabag.xxx.net/","method":"GET"} []
[2018-04-18 19:26:18] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2018-04-18 19:26:18] security.DEBUG: User was reloaded from a user provider. {"username":"kedare","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-04-18 19:26:18] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "The string to escape is not a valid UTF-8 string." at /var/www/wallabag/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig line 43 {"exception":"[object] (Twig_Error_Runtime(code: 0): The string to escape is not a valid UTF-8 string. at /var/www/wallabag/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig:43)"} []
[2018-04-18 19:26:18] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
```

**Comment by j0k3r** [comment]
This looks weird.
Did you add a content from a cyrillic langage?
You should remove content from each entry starting by the most recent until the homepage is working again. Then, please share the url related to the content which fails so we'll be able to produce a fix

**Comment by kedare** [comment]
Nop, just some French and Spanish, also a PDF, I'll do what you said and let you know the URL.

**Comment by kedare** [comment]
Ok I confirm this pdf breaks it : https://www.impots.gouv.fr/portail/files/media/10_conventions/espagne/espagne_convention-avec-l-espagne-impot-sur-le-revenu-impot-sur-la-fortune_fd_1824.pdf

**Comment by Tobi823** [comment]
Today I encounter the same issue when I added a document from my university (https://www2.ostfalia.de/export/sites/default/de/i/pruefungsangelegenheiten/pruefungsausschuss/2018-08-31-Leitfaden_Informatikstudium_Ostfalia_PO2010_13.pdf).

The titel of the webpage `Rahmenbedingungen – Bachelor Informatik und IT-Management` with the `–` character is the cause. The `–` is U+2013 (https://www.fileformat.info/info/unicode/char/2013/index.htm) and is the only character which is stored as 3 Bytes in UTF-8 (every other character only takes 1 Byte). You can use https://www.soscisurvey.de/tools/view-chars.php for checking the character value.

I could track down the issue to [https://github.com/wallabag/wallabag/blob/e586d65b64089fc1cc230a18c470aae3f45f91a6/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/Card/_content.html.twig#L5](https://github.com/wallabag/wallabag/blob/e586d65b64089fc1cc230a18c470aae3f45f91a6/src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/Card/_content.html.twig#L5) The `e('html_attr')` throws the 'The string to escape is not a valid UTF-8 string.' error. After replacing it with `e('html')` and deleting the tiwg cache with `rm -r var/cache/prod/twig` everything works and the link with the invalid UTF-8 is displayed as: `Rahmenbedingungen � Bachelor Informatik und IT-Management`.

The `–` (U+2013; stored as UTF-8: 0xE2 0x80 0x93; stored as UTF-16: 0x2013) was converted to `�` (U+FFFD; "\ufffd is the replacement character in unicode, it is used when you try to read a code that has no representation in unicode." from https://stackoverflow.com/a/24493972)

Quick fix: Replace e('html_attr') with e('html') but I dont know if this dangerous (because 'html' is not working as thoroughly as 'html_attr'. Also I think that 'html' is inappropriate because the value is being us as html attribute value . The twig documentation https://twig.symfony.com/doc/2.x/filters/escape.html could be better because I dont really understand the difference between html and html_attr.)

Real fix: Try to discover where the string is converted to an non-UTF-8-encoding. (I will try to do it but I dont know if I have the time for it)
