### ISSUE TITLE
White Screen of death / Using Wallabag without Nginx / Apache config changes

### ISSUE THREAD

**Issue by khromov** [wallabag/wallabag#3655]
### Issue details

I'm trying to set up a Wallabag instance and just can't wrap my head around why you require Apache / Nginx configuration just to run the `web/app.php` endpoint. A user needs to be able to set the service up reasonably easy on a bog standard web host by just uploading the content of a prepackaged zip. This is a huge and completely needless usability concern. At least something like `ln -s web/app.php web/index.php` should work.

After setting everything up via the git install + nginx config, I got a redirect to `/login` and then white screen of death without any error in the logs. Docs have no troubleshooting section. I'm trying to find something constructive to say but the installation experience is really sub-par compared to just about any other project I've used. 

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): ?
* php version: 7.0
* OS: Ubuntu 16.04.4 LTS (Xenial Xerus)
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

### Steps to reproduce/test case

N/A

**Comment by apiontek** [comment]
When I had that problem, it turned out to be solved by ensuring proper permissions as per https://doc.wallabag.org/en/admin/installation/rightaccess.html

I'm new to wallabag so I can't speak for the developers, but I run so many self-hosted apps with unique setups either proxied through nginx or configured in nginx that having just one more site configuration for wallabag was no big deal. I just set up another subdomain for wallabag and copied the nginx config from the docs into a new site config file with minor editing, and it worked, after ensuring the right permissions.

On ubuntu with nginx, you probably want to do a `chown -R www-data:www-data wallabag` on the parent folder.

**Comment by Bridouz** [comment]
Same whitescreen here,

It's weird because the **Wallabag** app for yunohost uses the same install process (except php5 instead of php7). And on Yunohost, Wallabag works

**Comment by khromov** [comment]
Thank you for the help @apiontek and @Bridouz . I got it to work, although I'm not sure if it was the file permissions or the nginx config that was incorrect. 

If anyone wants to set this up on EasyEngine, provided the root of your Wallabag installation is the `/var/www/your-domain.com/htdocs` folder, edit to `/etc/nginx/sites-enables/your-domain` to be something like this (use your own domain):

```
server {
    server_name your-site.com  www.your-site.com;
    access_log /var/log/nginx/your-site.com.access.log rt_cache;
    error_log /var/log/nginx/your-site.com.error.log;
    root /var/www/your-site.com/htdocs/web;
    index index.php index.html index.htm;

location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    location ~ ^/app\.php(/|$) {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass php7;
    }

    include common/locations-php7.conf;
    include /var/www/your-site.com/conf/nginx/*.conf;
}
```
