### ISSUE TITLE
Fails fetching the content from lundi.am

### ISSUE THREAD

**Issue by mxjeff** [wallabag/wallabag#3825]
### Issue details

Wallabag fails to fetch articles from lundi.am.

Looking at the log through "docker-compose logs" I only get the POST and 2 GET/200, nothing else. I did not tries to debug though.

### Environment

* wallabag docker image ''wallabag/wallabag  2.3.5  f22c35826fe0''
* docker-compose setup

I tried to fixed it installing php7-tidy as mentioned in #3806, but still failing.

### Steps to reproduce/test case

Fails on various pages, here are two of them:
  * https://lundi.am/Le-journal-d-Espagne-de-Simone-Weil-Bonnes-feuilles
  * https://lundi.am/Abecedaire-de-la-ZAD

**Comment by techexo** [comment]
Working flawlessly on f43.me, I'll try to have a look soon.

**Comment by techexo** [comment]
Actually in my graby _full debug mode_, the HTML full content is well retrieved, but I have no output after empty node stripping. 

It is due to the more than 2000 blank lines present in the code in between tags, that breaks the regex parser when trying to find empty nodes, because it is detected as a _runaway regular expression_ (even if it's not in this case).

I suppose that it works on f43.me because the "old" regex (before PR https://github.com/j0k3r/graby/pull/183) was actually not catching the empty lines (ironic, isnt'it... :smirk:).

Using the regex [described here](https://stackoverflow.com/a/709684) before the empty node stripping allows for the smooth retrieval of content:
```php
    // Remove empty lines
    $re = '/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/';
    $html = preg_replace($re, '\n', $html);
```

I'll PR that on graby.

**Comment by techexo** [comment]
@mxjeff The issue was a side-effect of a new code, which has been fixed in the master repository and will be deployed with the next release of wallabag. You can close the issue if you don't mind.
