### ISSUE TITLE
Warning during update

### ISSUE THREAD

**Issue by techexo** [wallabag/wallabag#3899]
### Issue details
Hi

It's probably nothing, but I have multiple warnings during the update from 2.3.6 to 2.3.7:
```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```
from the following files:
```
vendor/zendframework/zend-code/src/Reflection/MethodReflection.php
vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php
```

I reckon that the issue is not due to wallabag (as it's in the `vendor` directory), but we should probably echo this to the respecting repositories.

(Also, I was able now to update using directly the `make update` command, and it was niiiiiice! 😆)

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.7
* How did you install wallabag? Via `git clone` 
* php version: 7.3
* OS: Debian 9
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
As you said, as it's in vendor it's not related to wallabag so we can't fix it.
This will be fixed in wallabag 2.4 (as we are dropping PHP < 7.1 we can upgrade some packages). And in your case:
- zendframework/zend-code will be updated to ^3.3.0 because we upgraded ocramius/proxy-manager to ^2.1.1
- doctrine/orm will be update to v2.6.3 because we dropped PHP 5

So it will be fine on the 2.4.0 which will be fully compatible with PHP 7.2 (which might not be the case for the 2.3.*)

**Comment by mnvx** [comment]
@j0k3r May you fix PHP version in [Dockerfile](https://github.com/wallabag/wallabag/blob/master/docker/php/Dockerfile#L1)?

**Comment by gautamkrishnar** [comment]
You can simply set `ini_set('display_errors', 'Off');` in your web/app.php to disable this warning.
