### ISSUE TITLE
bad display of page elements

### ISSUE THREAD

**Issue by muralikodali** [wallabag/wallabag#3917]
i have installed wallabag version 2.38 on my ubuntu 18.04.1
web pages are lacking images and logos and display is showing only text elements.

my version of PHP is : **7.2.15**

i am able to login and use other features of wallabag instance without display  of images.
A screenshot showing the main page :
![img-2019-03-23-165120](https://user-images.githubusercontent.com/11482766/54865599-df160300-4d8d-11e9-8354-a702e6d83588.png)

**Comment by techexo** [comment]
Did you [check the permissions](https://doc.wallabag.org/en/admin/installation/rightaccess.html#production-environment) and cleared wallabag's cache (delete the content of the folder `wallabag/var/cache/prod`)?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by hermann-san** [comment]
I've the same problem with version 2.38 on CentOS, PHP 7.2 - shared hoster.
I haven't set any permissions since it's shared hosting and deleted the content of wallabag/var/cache/prod .
I've followed these instructions:  https://lab.uberspace.de/guide_wallabag.html
Except this layout problem, everything works fine with Wallabag.
Do you have any more suggestions on this issue?
Thanks.

**Comment by grayguest** [comment]
maybe https://github.com/wallabag/wallabag/issues/7023
