### ISSUE TITLE
Lost flexbox layout inside article

### ISSUE THREAD

**Issue by Rurik19** [wallabag/wallabag#3929]
Hi! 

[There is a good article](http://tobiasahlin.com/blog/masonry-with-css/) I want to wallabag to wallabag.it.

There are some flexbox formatted blocks, they looks like this:

![image](https://user-images.githubusercontent.com/1955806/56180740-1b065600-6024-11e9-9714-54e1c6a3e6ea.png)

but wallabag cut that just to unformatted \<P\>s.

![image](https://user-images.githubusercontent.com/1955806/56180826-66206900-6024-11e9-8db1-88d89d5fac00.png)

Is it common problem for flex elements?

**Comment by techexo** [comment]
It's totally normal, due to how graby and php-readability (the dependencies in charge of article fetching in wallabag) work.

wallabag is not a website dumper, but a textual content fetcher. So it needs websites with a semantically good html structure to work efficiently.

By default, div blocks are completely squashed by php-readability, as a div doesn't have a proper semantic function, it's just a block containing other contents. Your website is really a corner case, and I don't see how it will (nor why it should) be fixed, sorry.

**Comment by Rurik19** [comment]
Does Pocket use Graby too?
![изображение](https://user-images.githubusercontent.com/1955806/56198894-38074d00-6055-11e9-8ab3-5c07e4398f9e.png)

**Comment by Kdecherf** [comment]
> Does Pocket use Graby too?

Not as far as we know.

**Comment by techexo** [comment]
@Rurik19 Probably not, but they do have the same goal than us. `div` blocks are used for design, not for content; so there is no way for a content fetcher (like graby or Pocket's one) to know when blocks are meaningful (like here) and when they are useless from a content point-of-view (often). 

Furthermore, I think I'm not mistaken if I say that CSS are totally overriden during article fetching and processing; so even if `div`s were conserved, their style wouldn't.
For this special case, I think you're better off with a PDF print of the webpage than with wallabag or Pocket 😏

**Comment by Rurik19** [comment]
Evernote saved article OK. I think I should make select-and-save feature in the wallabagger...
