### ISSUE TITLE
The style sheets are missing

### ISSUE THREAD

**Issue by baskerville** [wallabag/wallabag#3938]
I was surprised to notice that the style sheets are missing from the exported ePUBs. They aren't even listed in the `/api/entries` responses.

Wallabag API: 2.3.8-dev.

**Comment by j0k3r** [comment]
What do you mean by "the style sheets"?

**Comment by baskerville** [comment]
I mean the CSS files referenced in the HTML *head* tag.

**Comment by j0k3r** [comment]
What I would like to understand is what is missing? Should ePUBs have html head tag with a missing CSS in it?

**Comment by baskerville** [comment]
The things that are missing from ePUBs are:
- The links to the CSS files (`<link href="/path/to/foo.css" rel="stylesheet" … />`) .
- The CSS files themselves.

**Comment by j0k3r** [comment]
From where these CSS comes from? Should there be hosted by wallabag? By the website itself?

**Comment by baskerville** [comment]
They come from the original page. I guess the hosting strategy should be the same as the one used for external images.

**Comment by j0k3r** [comment]
So thanks for finally put enough information so I can undestand what is your issue.
Wallabag extract only content and image from an url. We strip all the JS & CSS to only keep the content. That's why there is no CSS, no JS and the rendering is completely different from the original url. Because we focus on the content.

There won't CSS from the orignial url in the ePUB because we don't keep them as we don't need them to read the content.
