### ISSUE TITLE
Include composer.lock in repo

### ISSUE THREAD

**Issue by shtrom** [wallabag/wallabag#3946]
Wallabag ships a `Gemfile.lock` and `yarn.lock`. It would be usefull to also ship a `composer.lock`, providing a frozen list of known-tested dependencies for the PHP code.

This would also speed-up `composer install` calls, and hopefully reduce the needed memory.

I guess the lockfile could be bumped every release, or as needed when dependencies change or security issues pop up in some of them.

**Comment by tcitworld** [comment]
We bundle the `composer.lock` on each release (see https://github.com/wallabag/wallabag/pull/3896/files).

**Comment by shtrom** [comment]
I'm working off the branch `2.4` branch at the moment. Is there any reason not to keep it permanently, rather than just on releases?

**Comment by j0k3r** [comment]
We decide not to keep `composer.lock` in the repo because it generates to much conflict when someone update the `composer.lock` in a PR and the master diverge with other differences in the `composer.lock`. It might become a nightmare to rebase, rebase, etc.

Also, using `composer.lock` avoid to much memory to be used by composer when installing.
If someone want to try the master of wallabag, I guess he knows what it does and have enough memory allowed in PHP to handle a `composer up` instead of `install`.

That's why we decided to keep the `composer.lock` only in release.

**Comment by shtrom** [comment]
> Also, using composer.lock avoid to much memory to be used by composer when installing.

Yeah, that's exactly what I needed. I ended up generating on another machine, and it worked fine.

Thanks for the explanations!
