### ISSUE TITLE
Google search results redirects doesn't work - wallabag creates empty articles

### ISSUE THREAD

**Issue by mwoz123** [wallabag/wallabag#4259]
### Issue details

I reported an issue for wallabag-android https://github.com/wallabag/android-app/issues/899 but it turned out it's about server.

Once you search e.g. In Chrome Android browser in Google, Google seems to add /wrap real URL with their Google url.

So that url e.g.:
https://databox.com/google-my-business-seo

Is wrapped too :
https://www.google.com/url?sa=t&source=web&rct=j&url=https://databox.com/google-my-business-seo&ved=2ahUKEwiP-eu9x-LmAhVVxMQBHdRDDMwQFjABegQIAhAB&usg=AOvVaw1aBaNZBAs1MvqxLus1ZJGa

![Screenshot](https://user-images.githubusercontent.com/2197836/71785941-e9944700-3005-11ea-8b69-46d4f1c1b932.png) 

Wallabag server then creates incorrect articles for such urls:
![Screensho2t](https://user-images.githubusercontent.com/2197836/71785959-07fa4280-3006-11ea-808d-901f0912a591.png) 

with empty contents:
![Screensho3t](https://user-images.githubusercontent.com/2197836/71785961-0d578d00-3006-11ea-8c88-67852c1a7af5.png) 

Could you fix it?

### Steps to reproduce/test case
Described in issue details

**Comment by j0k3r** [comment]
See the associated PR on graby https://github.com/j0k3r/graby/pull/221
We already handled meta refresh url but in the wrong position for attributes.

Note that the associated domain to the entry will always be `google.com` because it's the first url. But the content will be well fetched for the targeted website.
