### ISSUE TITLE
Angular (javascript?) pages produces empty wallabag article

### ISSUE THREAD

**Issue by mwoz123** [wallabag/wallabag#4265]
# Issue details

Web pages written in Angular (might be also other Javascript generated) pages e.g.
https://angular.io/tutorial 
added to wallabag creates empty article:

![Screenshot_20200127-211150](https://user-images.githubusercontent.com/4487025/73210455-9fa50980-414a-11ea-8885-fd389e77c064.png)

### Environment

* wallabag version : framabag

### Steps to reproduce/test case
add page written in Angular to wallabag see how it's generated to article in wallabag

**Comment by j0k3r** [comment]
Yep we know but we can't fix it because the content is loaded using javascript and the parser doesn't interpret the javascript.

If the website doesn't do server side rendering for such case, we can't get the content.
Google can't get it either: http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fangular.io%2Ftutorial&oq=cache%3Ahttps%3A%2F%2Fangular.io%2Ftutorial&aqs=chrome..69i57j69i58.788j0j4&sourceid=chrome&ie=UTF-8

Unless we use a Chrome headless to fetch the page and then retrieve the generated HTML, we won't be able to fix.
I'm closing for _won't fix_.

**Comment by mwoz123** [comment]
Js frameworks for site building (like react, angular, vue etc) are becoming more and more popular each year. 
It's because they provide lot's of benefits for creating, assuring quality and maintaining sites compared to "traditional" /server side rendering way. 
From what I see (I'm web developer) nearly all new building/redesign sites are created using some modern web (based on js) framework. 

Are you sure you shouldn't think about supporting it?

**Comment by j0k3r** [comment]
I know.
We think about it but this is a huge improvement and we need to focus on sth else for now.
