### ISSUE TITLE
Fails to fetch data from https://www.alternativenation.net/

### ISSUE THREAD

**Issue by regagain** [wallabag/wallabag#4311]
Hi everyone,

I hope this is the right place to raise such issues.

### Issue details

Both Wallabag and f43.me fail to fetch data from https://www.alternativenation.net/, for example https://www.alternativenation.net/behind-the-scenes-layne-staley-final-concert-alice-in-chains/

### Environment

* wallabag version (or git revision) that exhibits the issue: **current version of wallabag.it, not sure how to check that**
* How did you install wallabag? Via `git clone` or by downloading the package? **I'm using wallabag.it**
* Last wallabag version that did not exhibit the issue (if applicable): **not applicable**

**Comment by j0k3r** [comment]
This is because that website use a server that ensure the client request has javascript enabled.
In order to bypass that we should interpret the first response to decode and create the cookie that'll allow us to parse the website.
This is far beyond simple rule in a site config.

See https://stackoverflow.com/questions/41005076/how-to-scrape-a-web-site-with-sucuri-protection
