### ISSUE TITLE
Solutions for restricted access articles

### ISSUE THREAD

**Issue by tcitworld** [wallabag/wallabag#438]
When an article is on a website which restricts access (most presumably because you are paying for it), several possibilities could be used to fetch content : 
- enter credentials and send them as a http header for sites which are compatible
- copy/paste content in wallabag
- save original article as a .html file and then import it in wallabag
- use a browser extension and send content via JS

However, all of this should be implemented as plugins in v2, not directly into Wallabag.

What do you think ?

**Comment by tcitworld** [comment]
@etiess on #886

>I copy here the input of necropotame in http://support.wallabag.org/discussions/questions/2-can-i-read-mediapart-with-wallabag
>
>Necropotame
>I have different parser, depending of the domain of the url. If it's mediapart.fr, then I load the page with this:

>        $opts = array(
>            'http'=>array(
>                'method'=>"GET",
>                'header'=>"Accept-language: fr\r\n".
>                "Cookie: SESS-COOKIE-NAME=COOKIE-VALUE\r\n"
>            )
>        );
>
>        $context = stream_context_create($opts);
>        $html = file_get_contents($url, 'FILE_NEXT', $context);

>It's hard coded, by you can imagine that people can them self attach a cookie to a domain. Or like with pocket, login to the website inside a specific windows which catch the cookie.

>One more thing about mediapart.fr : Default view for article divide the text into multiple pages. So the parser is not able to take the entire article. I do this transformation on the url to solve the  problem:


>        if(!preg_match("/onglet=full/", $url))
        {
            if(preg_match("/\?/", $url)) $url .= "&onglet=full";
            else $url .= "?onglet=full";
        }

>Support Staff 3 Posted by Nicolas Lœuille... on Oct 10, 2014 @ 02:08 PM

>Nicolas Lœuillet

>Nice, but you're right ... it's hard coded.
>We have to think about a cleaner solution.

>Necropotame

>I'm trying to solve this problem by keeping an sql table that describes an link source (identified by the domain name). I attach to each source a favicon, the source name, a color based on the favicon, a regexp to parse the title, a xpath to get the page content and the http option to download the page. And this http option can contains the session cookie.
The code of wallabag v1.* contains a folder with a list of parsing rules, so maybe it would be more interesting to move these rules to a database and let the user (or a parser) add more informations to each source (like favicon, but also session cookies).
I attach to this message a screenshot of my application to illustrate how favicon/color/source name can improve the application

**Comment by etiess** [comment]
I'm unfortunately not able to code, but if anybody wants to work on this feature and needs to test it, I can give my credentials for mediapart.fr and lemonde.fr

**Comment by etiess** [comment]
Some time ago, it was working on Pocket for mobile (tested on Android). See here: http://blog.ankh-morpork.net/Blog/Pocket-et-mediapart.fr
It gives a solution for the multiple pages issue too. But it doesn't seem to work anymore :(
Available to test if you need it.

**Comment by etiess** [comment]
And there's a Calibre recipe: https://github.com/kovidgoyal/calibre/blob/master/recipes/mediapart.recipe

**Comment by etiess** [comment]
An universal solution would be perfect. But for a first step, I'd chose a scheme with individual solution for each subscription site. As Calibre does. The problem is that we need to store the login and password into the server, and they shouldn't be stored in clear. Here are the steps I'd propose:
<OL>
<LI>Identify the priority websites:
<UL>
<LI>as a francophone, I'd propose Mediapart, which doesn't have any Android app
<LI>then Le Monde, Le Figaro, Libération, Arrêt sur Image, Rue89, and local newspaper (Parisien, Progrès, ...) 
<LI>for Anglophone websites: The Economist, The Times, Financial Times, NYT, Washington Post.
</UL>
<LI>Create the code to fetch a Mediapart article with Wallabag
<LI>Find a solution to not store the credentials unencrypted and be able to use them on the website.
<LI>Create the code for other listed subscription websites
<LI>(in the future): improve the solution in order to make it universal
</OL>
I would avoid a solution where an action from the user is needed each time he wants to save an article (copy/paste or HTML saving or login to the website)

**Comment by tcitworld** [comment]
We could extend siteconfig files in Graby (cc @j0k3r) to keep extra configuration to login (how cookies, sessions are handled). Then, credentials could be stored in a special table in a encrypted form.

Thing is, we'll need many accesses to those websites in order to test. :)

> I would avoid a solution where an action from the user is needed each time he wants to save an article (copy/paste or HTML saving or login to the website)

We agree on this.

At last resort, we can also use js from browser extensions to send the full content to wallabag.

**Comment by nicosomb** [comment]
> At last resort, we can also use js from browser extensions to send the full content to wallabag.

I think it's the only method to have a global solution: the bookmarklet send `document.documentElement.innerHTML` to wallabag and graby, instead of parsing a URL, parses HTML content.

**Comment by tcitworld** [comment]
The thing is, it's going to be more tricky to handle multi-page articles. Also, we'll need to modify the API.

**Comment by etiess** [comment]
@nicosomb I love to use Pocket today in this way:
* Right-click on the title of an article in my RSS reader, "Save to Pocket"
* Right-clik on a link pointing to an article, "Save to Pocket"
* On my mobile, long push on a link, "Save to Pocket"

The solution of using the browser is not a good solution for me, because it assumes that you already have opened the article you want to save in wallabag, isn't it?

**Comment by nicosomb** [comment]
@etiess with Firefox, you can already do the 2 first options: http://doc.wallabag.org/fr/Utilisateur/sauvegarder_son_premier_article.html#extension-mozilla-services-social-api

**Comment by etiess** [comment]
I know, and I'd like to be able to do the same with subscription website: in this case, if we expect to parse the HTML and not the URL, I understand that it would not work. Is it correct?

And if we depend on the browser, the solution for the wallabag mobile applications won't be easy.

**Comment by j0k3r** [comment]
Solution from Pocket is interesting. But I guess they need to store login/password somewhere for each custom subscription website.
About the cookie solution, we are going to be limited to the session time. When the session will expire, we are going to lose it and the cookie won't work.
Sending content using a browser extension could be an idea but it will only work on a desktop browser and won't fetch additional pages.

There is no _good_ solution for the moment :confused:

**Comment by bdunogier** [comment]
Hey there. I'm the author of the article above about Mediapart & Pocket, an aging PHP dev and heavy Pocket user.

I have worked on a project called [mediapart proxy](https://github.com/bdunogier/MediapartProxy). to get content from mediapart.fr and mondediplomatique.fr (don't forget this one :p) into Pocket. As you can see, it is _also_ a Symfony application, with re-usable bits (look into https://github.com/bdunogier/MediapartProxy/tree/master/src/BD/SiteReaderProxy/LmdSiteBundle for). 

The idea is that plugins for each site take care of each login event (expired session, re-authentication, etc etc). The proxy approach allowed me to integrate the sites into any reader solution (and also to shared payed articles to close relatives on occasions).

Since it's vacation time, I was thinking of fixing my proxy, as it just doesn't work anymore. I've spent the last hour looking into the wallabag architecture to see how I could maybe integrate what I have done there. I have reached the conclusion that we may have to extend Graby instead of Wallabag. 

Unfortunately, what i've seen of Graby's code is very very appealing in terms of extensibility. I'll nonetheless keep looking a bit into it. There's probably something we can do. 

If somebody wants to discuss the topic, I'm available :-)

**Comment by j0k3r** [comment]
Yeah integrate your solution into graby is a good option.

Maybe you should release your proxy as a standalone library that anyone can use and it'll be easy to integrate it inside graby (with a kind of url detection for each provider of your proxy (mediapart & lmd)).

If you want to talk about that we are available in [Gitter](https://gitter.im/wallabag/wallabag) :)

**Comment by bdunogier** [comment]
I was indeed thinking of keeping this external, so that we have the headers/cookies we need _passed to grabby_.

The separation you mentioned is a good one, yes. My proxy would use the libraries and act as an independent solution, and wallabag could use it to handle sites auth.

**Comment by bdunogier** [comment]
Posted a proof of concept to #1536.

**Comment by etiess** [comment]
Hello everybody,

Now that Wallabag V2 is launched (congratulation by the way!), is something possible on this issue? Available to test if you need it.
And for information, Mediapart (finally) launched its Android app: https://play.google.com/store/apps/details?id=com.mediapart.app

**Comment by bdunogier** [comment]
Hey there.

I have been completely unable to spend time on this. Way too much already with family + work.

I haven't given up though, but if somebody wants to give hir opinion on the latest comment and/or think of the proper way to store/configure passwords: by all means do :)

**Comment by etiess** [comment]
Hi there,
Did somebody find some time to work on this feature? That's the missing piece for my perfect wallabag ;) Still available to test...

**Comment by etiess** [comment]
I saw that @nicosomb tried @bdunogier 's PR https://github.com/wallabag/wallabag/pull/1586#issuecomment-244862231
What's next? Available to test if you need to.

**Comment by nicosomb** [comment]
I need a mediapart account (just for one month) 😇  ...

**Comment by nicosomb** [comment]
@etiess It works for mediapart.fr and arretsurimages.net. This feature will be in wallabag 2.2.

**Comment by etiess** [comment]
Yes! Thank you everybody, that's great!

**Comment by nicosomb** [comment]
Just opened a new PR #2317.
