### ISSUE TITLE
Make the installation more user-friendly

### ISSUE THREAD

**Issue by nicosomb** [wallabag/wallabag#466]
Today, as you know, installing wallabag is not sexy. 

In this issue, give us your ideas to improve it.

**Comment by Poorchop** [comment]
Installation is as far from user friendly as it can get. I am trying to install in Arch and it has been a nightmare so far. I haven't tried using composer because I don't want to install it, so I've been following the manual instructions and I just can't set it up.

The documentation cuts out 90% of the steps needed to even simply access wallabag in your browser. You need to install to a different directory and create an nginx configuration manually. When you finally get everything set up properly, installation fails at "Install vendor.zip," and yes I already have the zip extension enabled in my PHP config. I had to look at the source code to manually get the url for vendor.zip. I also noticed that wallabag kept trying to install in the cache folder, so that's where I extracted vendor.zip, but it turns out that the vendor folder needs to be in the root wallabag folder.

Finally onto the next step. I click "Install wallabag," but then I'm just taken to a blank page. Check the error log and it's a permissions issue. I don't even know which folders needs write permissions, but I don't want to start chmodding random folders.

If someone can help me out with this issue, then I can do a thorough writeup for manually installing. Hopefully it will alleviate headaches for others down the line, but it still won't be a very user friendly installation.

**Comment by tcitworld** [comment]
Sorry for the problems you encountered.

The documentation is not up to date with latest version, it should explain why you did find it hard.

> You need to install to a different directory and create an nginx configuration manually. 

Hmm, no it should work with default config host file at the default location. 

> When you finally get everything set up properly, installation fails at "Install vendor.zip," and yes I already have the zip extension enabled in my PHP config.

This may have failed because you didn't have correct rights on the folders. Or that you can't use the `fopen` function. Or that our host rejected your server (unlikely).

> I had to look at the source code to manually get the url for vendor.zip.

An [error message](https://github.com/wallabag/wallabag/blob/master/install/index.php#L32) should have been shown, displaying the url. Quite strange.

>  I also noticed that wallabag kept trying to install in the cache folder, so that's where I extracted vendor.zip, but it turns out that the vendor folder needs to be in the root wallabag folder.

Yeah, the cache folder is used as the temporary folder.

> Finally onto the next step. I click "Install wallabag," but then I'm just taken to a blank page. Check the error log and it's a permissions issue. I don't even know which folders needs write permissions, but I don't want to start chmodding random folders.

The `assets`(if you download pictures), `cache`, `db` (if SQLite is used) and `inc` should have `chmod 775` and `chown yourwebserveruser`.

I'll try to find time to update and really improve documentation. But at the same time v2 will come out in one month or two and the installation will be completely different.

Please write back if you have any further issues.

**Comment by Poorchop** [comment]
Hi @tcitworld, I managed to get wallabag working. I was going to edit my comment but I got sidetracked and completely forgot.

Some of my problems might be specific to Arch. I remember encountering issues with selfoss installation when uploading the folder to /var/www/, and the error logs pointed me to a few other directories instead, /usr/share/webapps/ being one of them. I will dig through the error log again to figure out the specifics of this issue.

You are correct in that some of my issues where because I didn't have the proper rights on the folders. I was browsing through the wallabag help forums and saw a similar issue from another user that was rectified by changing the owner to www-data. In my case, `chown -R http:http /usr/share/webapps/wallabag/` did the trick. I was going to add that to the help forum person but I didn't see an option to comment on that thread.

As for vendor.zip, I didn't see the URL because wallabag was apparently able to open the URL to begin download of the file, but I guess it couldn't unzip it. I got the error message [on this line](https://github.com/wallabag/wallabag/blob/7d6bd5670e8743e10c52b745142320a47d0f1cbe/install/index.php#L38) instead, but when I went to manually unzip the file, it failed, maybe because the download was incomplete.

I would be happy to contribute to the documentation, but if wallabag 2 is coming soon, then I guess it isn't necessary. Once the user works out the small issues with permissions and creating the necessary nginx conf, installation isn't so bad. The plugin checker in the web install portion was a really nice touch and thanks to that little table, I was able to inadvertently fix a problem I was having with selfoss.

Hopefully I can help out with the v2 docs if needed. Otherwise, really excellent piece of software.

**Comment by Poorchop** [comment]
@tcitworld I think this issue should be closed. After installing wallabag in a few other distros, it turns out that most of my problems were distro-specific and a result of incorrectly setting up PHP and PHP-FPM. The actual setup of wallabag alone is as straightforward as possible so if anything, the documentation needs to be improved, not the installation procedure. However, like you said, v2 will be coming out soon so there is no need to change the documentation right now.

**Comment by LeBaux** [comment]
I have to agree... lower-level admins like me are pretty likely to fail the installation. It should be as easy as installing wordpress - upload & run, then during the installation process fill the database and check the dependencies.

**Comment by tcitworld** [comment]
Are you still talking about v1 ?
