### ISSUE TITLE
personalized Reading time is not correct in the tagging rules evaluation

### ISSUE THREAD

**Issue by Strubbl** [wallabag/wallabag#4935]
### Environment

* **Version**:2.4.1 (also 2.4.3)
* **Installation**:git
* **PHP version**:
* **OS**:Debian stable
* **Database**:PostgreSQL
* **Parameters**:

### What steps will reproduce the bug?
1. Change reading speed to your level.
2. create a tagging rule, which evaluates the reading time of the article. 
3. add an article
4. see that the tag or wrong tag has been set to your article

Just an example:

e.g. i have a reading speed of 100 words per minute. I add an article, where wallabag tells me it's a 12 min read. i have a tagging rule, that when reading time is equal or more than 10 min, it's a #longread. and a second tagging rule for article's reading length smaller than 10 min, that's a #shortread.
Although with my personal reading speed of 100 words per minute, wallabag correctly tells the reading time is 12 min, but it tags the article with #shortread. I would have expected it to be #longread because 12>10.

This was working before wallabag version 2.4.0. I guess it was 2.3.8, which i had installed before.

**Comment by Strubbl** [comment]
is the fix from #5405 also applicable here?

**Comment by Kdecherf** [comment]
@Strubbl after looking at the code really quick I don't think so

**Comment by j0k3r** [comment]
I think the problem is because the `reading_time` of each entry is based on a hard coded 200 words per minute, see https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Tools/Utils.php#L29-L32

So, if you change your word per minute, it'll be properly displayed in the UI (because we recalculate it when displaying the value) but nothing changed in the database. The reading time of the entry will remain the same in the database no mater what value you personally define.
