### ISSUE TITLE
RecordFactory.php in MOBIClass leads to server error 500

### ISSUE THREAD

**Issue by schoenf** [wallabag/wallabag#5151]
```
if (!function_exists('mb_str_split')) {  // ADDED
        function mb_str_split($string, $split_length = 1)
        {
            mb_internal_encoding('UTF-8');
            mb_regex_encoding('UTF-8');

            $split_length = ($split_length <= 0) ? 1 : $split_length;

            $mb_strlen = mb_strlen($string, 'utf-8');

            $array = array();

            for ($i = 0; $i < $mb_strlen; $i += $split_length) {
                $array[] = mb_substr($string, $i, $split_length);
            }

            return $array;
        }
} // ADDED
```

Since mb_str_split() is a built-in function in newer PHP releases, the redefinition here is invalid and needs to be done only if the function is not already declared.

I would have committed this change on my own, but have no write access to the git repository at github.

Greetings,

Jochen

**Comment by j0k3r** [comment]
Hello Jochen,

First you should fill the issue template when asking for it https://github.com/wallabag/wallabag/issues/new/choose
It helps use know your env. Otherwise we just want to close your issue without checking to avoid losing time.

Second, that function is already removed since 2 years now https://github.com/wallabag/php-mobi/commit/bfe9c18d038e5ca24664cfdab107a645ac57c9b5

Finally, you don't need to have write access to the GitHub repository to submit your changes.

**Comment by schoenf** [comment]
Okay, thank you. I don't know why I didn't get the latest version of all files when using "git pull", but I have renamed my wallabag directory and did a new "git clone". Now everything works fine without any change. And looks much nicer than before.
