### ISSUE TITLE
Add comment about wallabaged page

### ISSUE THREAD

**Issue by Lamecarlate** [wallabag/wallabag#592]
Sometimes I use wallabag to save a page and would like to add a comment, a little text of my own : "Write article about that because I disagree", "Superduper CSS technique I have to test"... A bit like Shaarli does, but just for me.

(it's a proposition of enhancement, not a bug)

**Comment by nicosomb** [comment]
Do you think this library http://aroc.github.io/side-comments-demo/ could be a good thing?

**Comment by tcitworld** [comment]
It stores comments in a special json file, maybe we could include this in our own database ?

**Comment by nicosomb** [comment]
Will be added via #1421.

**Comment by tcitworld** [comment]
Bookmark. https://github.com/openannotation/annotator

**Comment by Kwadz** [comment]
I think Annotator is more accurate and suitable because it allows to highlight linked text to the comment. It seems to be the best annotation open source tool at this moment. 
I truly believe it is the main missing component to compete with paid solution as Diigo and Scrable which provide saving web pages and annotation tool.
Do you plan to integrate it?

**Comment by tcitworld** [comment]
I guess so, even though I started work.

**Comment by tcitworld** [comment]
I'm currently looking into porting the Annotator Storage to Symfony.

**Comment by Kwadz** [comment]
Yeah ! This is a great idea :-)

**Comment by tcitworld** [comment]
It's partly done, check out https://github.com/wallabag/wallabag/pull/1653

**Comment by nicosomb** [comment]
It's totally done :+1:
