### ISSUE TITLE
Vimeo videos are not correctly resized

### ISSUE THREAD

**Issue by romu70** [wallabag/wallabag#6851]
### Environment

* **Version**: 2.6.2
* **Installation**: Docker image
* **PHP version**: 
* **OS**:
* **Database**: Postgres 15
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  PASTE HERE
  ```
</details>

### What steps will reproduce the bug?

I saved this [link](https://legrandcontinent.eu/fr/2023/08/03/jai-eu-des-doutes-deux-conversations-avec-robert-oppenheimer/).

Arround the middle, there is a Vimeo video which is not correctly resized by wallabag. Check this screenshot.

![IMG_0091](https://github.com/wallabag/wallabag/assets/1898319/3717a9a7-1daf-4456-90c9-1f345e1b1b1a)

**Comment by HolgerAusB** [comment]
The image size, or better the iframe size, is hard coded in the source by `<iframe ... width="1280" height="720"... `

We could strip the width and height parameter which makes the video preview very mini. We could not change the w/h values by site_config rule.

I already did a new site_config, because of your other issue. But is that really what you want, @romu70? Please answer, so I can upload my site-config.

Here the screenshot with my new site_config:

![grafik](https://github.com/wallabag/wallabag/assets/3876469/0b35f7d4-d677-4699-8b47-bc0e9543d01f)

**Comment by romu70** [comment]
Thanks for this quick feedback.

I'd better think of having it responsively resized to use the maximum width of the reading area depending on the device used.

**Comment by HolgerAusB** [comment]
me too, but that is not possible at the moment. That needs changes to graby. So you can have the small or the large one now.

as self-hoster you could do ugly things like:
```
replace_string(width="1280"): width="640"
replace_string(height="720"): height="360"
```
But that would count for all elements in the source and could cause unforeseen problems.

While I just strip the attributes with:
```
strip: //iframe/@width
strip: //iframe/@height
```

**Comment by HolgerAusB** [comment]
@j0k3r I think, this should be closed too, as there is no way to resize the video iframe dynamically to the users screen size
