### ISSUE TITLE
Add .mobi export

### ISSUE THREAD

**Issue by aschilling** [wallabag/wallabag#701]
Hi everybody,
In addition to the epub export it would be great to support also mobi export. I did some research and found this interesting project https://github.com/raiju/phpMobi. Maybe you can have a look at it and consider using it for wallabag.
Thanks

**Comment by tcitworld** [comment]
This is ready in dev version.

**Comment by tristan-k** [comment]
I tested the dev version and have to say that I'm a little bit disappointed about the implementation. Don't get me wrong - I'm grateful for the mobi export, but will it be possible to export single articles rather than everything? I noticed that the export also exports the articles which are in the archive. Not so handy if you just want to read a single article on your kindle and accessing wallabag through the buildin kindle browser.

**Comment by tcitworld** [comment]
Mobi export can be done on every article, category, tag or even search. It it doesn't, then there's a bug.

**Comment by tcitworld** [comment]
Sorry, you need to activate mobi export in inc/poche/config.inc.php

My mistake.

**Comment by tristan-k** [comment]
Thanks! Works great.

**Comment by tcitworld** [comment]
I will delete the link for mobi/pdf export in config screen when there are not enabled.

**Comment by tristan-k** [comment]
I just noticed that the kindle beta browser isnt able to download any mobi-files with spaces inside the filename. This way the files will not be added to kindle. Please change the filename generator so that spaces (or "%20") will be replaced by underscores.

**Comment by tcitworld** [comment]
Can you give me an URL which leads to this kind of error to work with ?

**Comment by tristan-k** [comment]
I dont know if you have access to any Kindle devices. Its more like a limitation of the inbuilt browser of the Kindle, because it is unable of handling spaces in filenames. I'm using a Kindle Touch Paperwhite with Firmware Version 5.4.2. If you log in to any wallabag instance and try to download the mobi-version of an article with spaces, than a mobi-file like "filename%20with%20spaces.mobi" will be generated. The Kindle Beta Browser says it will be downloading the file, but actually it will not be saved because of the spaces. I generated a mobi-file of an article with just a single word and therefore without spaces in the filename and it downloaded just fine.

**Comment by tcitworld** [comment]
Quick note : *I don't own any Kindle devices. To view how mobi files rendered I used Calibre, which seems to have rather good compatibility and sometimes I sent myself an email to add the documents at my collection and view it on their mobile apps, so I really don't know how they display on actual devices.*

On the subject of having spaces in the filename, I just fixed that.

**Comment by tristan-k** [comment]
Thanks! It seems the kindle beta browser also cant handle quotation marks or any other special characters. Maybe you could change the character encoding?

**Comment by tcitworld** [comment]
Now I've limited filenames at alphanumeric characters. Can't think I can do better. ;)

I'm thinking I may cut the filename at a certain number of characters.

**Comment by tristan-k** [comment]
Great! Now it works.
