### ISSUE TITLE
Websites Articles from pflege-online.de not well displayed

### ISSUE THREAD

**Issue by syrabo** [wallabag/wallabag#7113]
Hello,

articles from pflege-online not well displayed.

such as: https://www.pflegen-online.de/delir-5-haeufige-ausloeser-und-7-kluge-reaktionen

Best regards

**Comment by HolgerAusB** [comment]
That was a hard one. Because of badly used script inside I could not use `body: //article[1]`, wallabag tries to remove `<script>` tags but failed to do so and everything after the section 2 was missing. (FTR worked fine with that). So I had to concatenate the parts, which hopefully will fit all sorts of articles on that site.

@syrabo if you are a self-hosting wallabag copy file `pflegen-online.de.txt` from https://github.com/fivefilters/ftr-site-config to
`<wallabag>/vendor/j0k3r/graby-site-config`

and clear the cache before refetch. e.g. for debian systems:
`sudo -u www-data <wallabag>/bin/console --env=prod cache:clear`

If you find articles which fail, pst their urls.

If you are subscriber to app.wallabag.it, you have to wait for the next release

**Comment by syrabo** [comment]
Thank you. I use app.wallabag.it  with many thanks for this great tool.
