### ISSUE TITLE
Wrong display in wallabag (steve-yegge.medium.com)

### ISSUE THREAD

**Issue by kindlyfire** [wallabag/wallabag#7652]
**Before submitting the issue, please read:**
If wallabag can't parse / extract content for a given link, please first read the documentation about it:
http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

- [x] I've tried myself without success
- [x] I've replaced `HOST` in the issue title with the host of the URL that can't be fetched (ie: `nytimes.com`, `20minutes.fr`, `bbc.com`, etc.)

**Content related:**
 - URL: [link](https://steve-yegge.medium.com/dear-google-cloud-your-deprecation-policy-is-killing-you-ee7525dc05dc)
 - wallabag version: 2.6.6 (hosted app.wallabag.it)

**Describe what's wrong:**
I get the error "wallabag can't retrieve contents for this article".  I've tested it through [f43.me](https://f43.me/feed/test) as the help article says and that works.

**Comment by HolgerAusB** [comment]
The problem here is, that medium is blocking requests from app.wallabag.it. If you are using Firefox or Chrome on desktop, you may want to install the browser extension 'wallabagger' and activating 'Content fetching from the browser' option in the plugin's options.

This plugin makes it also possible to catch paywalled articles, if you are a subscriber and logged-in to the source site.

**Comment by kindlyfire** [comment]
That works. I'll close since it's just for app.wallabag.it, then.
