### ISSUE TITLE
Reporting issue via email failed

### ISSUE THREAD

**Issue by RayBB** [wallabag/wallabag#7838]
This isn't a bug with wallabag app/service.
However, when I sent an email with a config issue recently it bounced back.

```
This is the mail system at host [mut-zose1-mta-hub-in01a-fr.yulpa.io](http://mut-zose1-mta-hub-in01a-fr.yulpa.io/).

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<[rle973dl@robot.zapier.com](mailto:rle973dl@robot.zapier.com)>: host [mx-out-ncp1.yulpa.io](http://mx-out-ncp1.yulpa.io/)[185.49.21.250] said: 550
    High probability of spam (in reply to end of DATA command)
```

<img width="601" alt="image" src="https://github.com/user-attachments/assets/30be2e71-c780-42ea-b3d7-3c45d70fd8c0">

The complete text of the message I sent.

<img width="523" alt="image" src="https://github.com/user-attachments/assets/047d3388-7357-4b10-9dbc-b4fe04de3f69">

**Comment by HolgerAusB** [comment]
Maybe zapier registered an uncommon amount of mail from your address within short time (few days). Because it 'High probability of spam'. Normally the bot didn't see more than two or three mails in a week from a single mail-address.

By the way: When posting new issues about wrong fetches (by mail or directly in github), please add the domain/host to the subject line: **Wrong display in wallabag (example.com)**
