### ISSUE TITLE
Wrong display in wallabag

### ISSUE THREAD

**Issue by RayBB** [wallabag/wallabag#7839]
https://www.classcentral.com/report/duolingo-vs-coursera-udemy-worth-comparison/

Manually posting since #7838

**Comment by HolgerAusB** [comment]
@RayBB unfortunately this site uses bot prevention by cloudflare, which denies the content to wallabag. You have to use "wallabagger" browser extension here  with activated option 'Retrieve content from the browser' in it's settings.

**Comment by RayBB** [comment]
@HolgerAusB one question.
Is there any feature request open (I looked but didn't see it) to notify in the web UI when a config needs to be saved from Wallabagger to work? That would be really handy :)

Thanks!

**Comment by HolgerAusB** [comment]
afaik I did post that issue or a similar one. But wallabag can't find out itself, what the problem is. So the error message will always be the same.

I agree that the text could be more detailed and/or more helpful. A reference to a wiki article on GitHub would also be conceivable, then you could find newer, current solutions regardless of the releases.

@j0k3r what do you think?
