### ISSUE TITLE
Blogger Articles show up as untitled

### ISSUE THREAD

**Issue by anno1337** [wallabag/wallabag#803]
I tried saving the following article to my wallabag setup: http://www.gavinj.net/2012/06/building-python-daemon-process.html

This uses one of these rather silly javascript templates which seems to cause problems with wallabag. No content is saved.

**Comment by j0k3r** [comment]
Thanks for reporting that blogger website.
Of course, as FTRSS, graby put a `_escaped_fragment_` to get the html.

The problem here is that this website use a data-uri image as the open graph image. So the body is huge and graby (should be the same for FTRSS) don't check too much html to be able to detect that fragment.

It'll be fixed in the 2.0.2.
