### ISSUE TITLE
Pluxml

### ISSUE THREAD

**Issue by qwertygc** [wallabag/wallabag#976]
Hello !
Les sites sous pluxml type orangina rouge ou cyrille borne ne se mettent pas comme il faut dans wallabag.
Bonnes fêtes !

**Comment by Trim** [comment]
I've just sent a mail to report same bug (sorry) with some details:

http://www.cyrille-borne.com/article378/astuce-augmenter-la-taille-d-un-disque-virtuel-vdi-de-virtualbox

When I bag it, I've only the website main titles instead of the article.
Indeed, it seems to take only the titles into the <aside> tag which is
the website menu instead of the <article> tag included in the <section>.

Thanks!

**Comment by j0k3r** [comment]
Looks good to me on the v2
